### ISSUE TITLE
Can not import dbsClient when using crab3-bootstrap script

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4572]
```
$ cmsenv
$ alias crab='/cvmfs/cms.cern.ch/crab3/crab-env-bootstrap.sh'
$ crab submit -c crabConfig_report.py
Error during CRAB3 bootstrap:
CRAB configuration syntax error: Unable to load Configuration File:
/afs/cern.ch/work/a/atanasi/crab3/CMSSW_7_3_5_patch2/src/crabConfig_report.py
Due to error:
No module named dbs.apis.dbsClientTraceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1510/lib/python2.6/site-packages/WMCore/Configuration.py", line 560, in loadConfigurationFile
    modPath[1], modPath[2])
  File "/afs/cern.ch/work/a/atanasi/crab3/CMSSW_7_3_5_patch2/src/crabConfig_report.py", line 1, in <module>
    from CRABClient.UserUtilities import config, getUsernameFromSiteDB
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1510/lib/python2.6/site-packages/CRABClient/UserUtilities.py", line 14, in <module>
    from dbs.apis.dbsClient import DbsApi
ImportError: No module named dbs.apis.dbsClient
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
```

**Comment by belforte** [comment]
should be solved at same time https://github.com/dmwm/CRABClient/issues/4583

**Comment by belforte** [comment]
solved by introduction of crab light client see #4583
