### ISSUE TITLE
make sure to test crab remake

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4659]
I got an odd error using crab remake in my development verion of the client (aligned with master in dmwm) [1]
I do not think it is worth to investigate now. But please make sure to test crab remake before releasing new client. It is seldom used by users, but it is used a lot by me for troubleshooting user problems

[1]
```
belforte@lxplus0051/nick> crab remake --task 161215_190607:namin_crab_ttZJets_13TeV_madgraphMLM_RunIISummer16MiniAODv2-80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1

=====================================
ERROR: AttributeError: remake instance has no attribute 'serverurl'
```

**Comment by belforte** [comment]
By the way, production client works:
```
belforte@lxplus0051/nick> which crab
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/bin/crab
belforte@lxplus0051/nick> crab remake --task 161215_190607:namin_crab_ttZJets_13TeV_madgraphMLM_RunIISummer16MiniAODv2-80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1
Remaking crab_ttZJets_13TeV_madgraphMLM_RunIISummer16MiniAODv2-80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1 folder.
Remaking .requestcache file.
Success: Finished remaking project directory crab_ttZJets_13TeV_madgraphMLM_RunIISummer16MiniAODv2-80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/nick/crab.log
belforte@lxplus0051/nick>
```

**Comment by belforte** [comment]
and this is the traceback from the failure:
```
ERROR 2016-12-23 10:06:41,696: 	 Unhandled Exception!
ERROR 2016-12-23 10:06:41,697: 	 remake instance has no attribute 'serverurl'
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 160, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 325, in __init__
    delattr(self, 'serverurl')
AttributeError: remake instance has no attribute 'serverurl'
ERROR 2016-12-23 10:06:41,697: 	 ERROR: AttributeError: remake instance has no attribute 'serverurl'

```

**Comment by emaszs** [comment]
Works fine AFAIK.
