### ISSUE TITLE
crab client crash on some sandbox upload failures

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4700]
here's an example from the problem reported by a user
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2853.html
It looks to me that this line is indented one level too many
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/Analysis.py#L162
so when there is an exception other than file too large, the code falls through to line 168 and following w/o uploadResult being defined

```
DEBUG 2017-05-07 17:08:21,246: 	 Uploading archive /afs/cern.ch/work/a/amohamed/llvv80/Nickcode/CMSSW_8_0_27/src/Analysis/monoZ/crab/crab_monoZ_05May2017_SMM_MonoZ_Mphi-300_Mchi-100_gSM-1p0_gDM-1p0_13TeV-madgraph/inputs/debugFiles.tgz (4 KB) to the CRAB cache. Using URI https://cmsweb.cern.ch/crabcache
ERROR 2017-05-07 17:08:21,547: 	 Unhandled Exception!
ERROR 2017-05-07 17:08:21,547: 	 local variable 'uploadResult' referenced before assignment
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/bin/crab", line 148, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 99, in __call__
    dummy_inputfiles, jobconfig = plugjobtype.run(filecacheurl)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/lib/python2.7/site-packages/CRABClient/JobType/Analysis.py", line 180, in run
    configArguments['cachefilename'] = "%s.tar.gz" % uploadResult
UnboundLocalError: local variable 'uploadResult' referenced before assignment
ERROR 2017-05-07 17:08:21,548: 	 ERROR: UnboundLocalError: local variable 'uploadResult' referenced before assignment
ERROR 2017-05-07 17:08:21,548: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2017-05-07 17:08:21,548: 	 	Client Version: 3.3.1705.patch1
```

**Comment by belforte** [comment]
maybe note really that indentation
there could be an HTTPException w/o  'X-Error-Info' in hte.headers
@emaszs rightfully pointed out that we should `raise hte`

**Comment by emaszs** [comment]
Indeed, an unrelated http error that was ignored since we removed the `raise hte`. The sandbox-too-big exception shouldn't really happen ever unless people start modifying their CRABClients and bypassing the client-side check. Anyway, I'll make a PR

**Comment by belforte** [comment]
sorry, I clearly introduced this when added the message about sandbox size :-(
