### ISSUE TITLE
Certificate verify failed error in new status command

### ISSUE THREAD

**Issue by emaszs** [dmwm/CRABClient#4703]
The new status fails to download the status_cache file from the schedd when running the client from outside CERN it seems [1]. I believe only clients using CMSSW versions which have python versions >= 2.7.9 are affected (>= CMSSW_8_*_* ?). Stefano pointed out a change in python that is very likely the reason for this error [2]. Alan has also noticed this issue in production [3], the solution appears to be setting the SSL context correctly. I will first try to reproduce this error, then see how to solve it. Since this is the only place in our code which is using urllib for a request, it may be better to rewrite it in pycurl for consistency.

[1]
```
INFO 2017-05-07 17:39:49,681: 	 CRAB project directory:		/grid_mnt/public/sobhatta/PhD/source2custom/CMSSW_8_0_20/src/crabJobs/crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
INFO 2017-05-07 17:39:49,681: 	 Task name:			170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
INFO 2017-05-07 17:39:49,681: 	 Grid scheduler:			crab3@vocms0119.cern.ch
INFO 2017-05-07 17:39:49,681: 	 Status on the CRAB server:	SUBMITTED
INFO 2017-05-07 17:39:49,681: 	 Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/170506_131227%3Asobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
INFO 2017-05-07 17:39:49,681: 	 Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=sobhatta&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=170506_131227%3Asobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
DEBUG 2017-05-07 17:39:49,681: 	 The CRAB server submitted your task to the Grid scheduler (cluster ID: 6364333)
DEBUG 2017-05-07 17:39:49,682: 	 Webdir is located at http://vocms0119.cern.ch/mon/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
DEBUG 2017-05-07 17:39:50,794: 	 Proxied webdir is located at https://cmsweb.cern.ch/scheddmon/0119/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8
DEBUG 2017-05-07 17:39:50,795: 	 Retrieving 'status_cache' file from https://cmsweb.cern.ch/scheddmon/0119/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8/status_cache
INFO 2017-05-07 17:39:51,155: 	 Waiting for the Grid scheduler to report back the status of your task
DEBUG 2017-05-07 17:39:51,155: 	 Cannot retrieve the status_cache file. Maybe the task process has not run yet?
Got: Error while trying to retrieve file from https://cmsweb.cern.ch/scheddmon/0119/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8/status_cache: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)
Make sure the URL is correct.
ERROR 2017-05-07 17:39:51,155: 	 Error while trying to retrieve file from https://cmsweb.cern.ch/scheddmon/0119/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8/status_cache: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)
Make sure the URL is correct.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 105, in __call__
    statusCacheFilename = getFileFromURL(url, filename=filename, proxyfilename=self.proxyfilename)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch1/lib/python2.7/site-packages/CRABClient/UserUtilities.py", line 150, in getFileFromURL
    raise exc
ClientException: Error while trying to retrieve file from https://cmsweb.cern.ch/scheddmon/0119/cms1428/170506_131227:sobhatta_crab_TT_TuneCUETP8M1_13TeV-powheg-pythia8/status_cache: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)
Make sure the URL is correct.
INFO 2017-05-07 17:39:51,181: 	 Error: Status information is unavailable, will not proceed with the resubmission. Try again a few minutes later if the task has just been submitted.
INFO 2017-05-07 17:39:51,187: 	 Log file is /grid_mnt/public/sobhatta/PhD/source2custom/
```
[2]
https://docs.python.org/2.7/library/urllib.html?highlight=urllib.urlopener#module-urllib
[3]
https://github.com/dmwm/WMCore/issues/7821

**Comment by belforte** [comment]
+1

**Comment by belforte** [comment]
I could reproduce the problem in Pisa with a few python lines which mimic
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/UserUtilities.py#L116

```
>>> url="https://cmsweb.cern.ch/scheddmon/0119/cms574/170509_212924:santocch_crab_MET_E/status_cache"
>>> from urlparse import urlparse
>>> parsedurl = urlparse(url)
>>> import os
>>> import urllib
>>> proxyfilename=os.getenv('X509_USER_PROXY')
>>> opener = urllib.URLopener(key_file = proxyfilename, cert_file = proxyfilename)
>>> socket = opener.open(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-oenich2/lib/python2.7/ssl.py", line 815, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)
>>> 
```

the error hints to the host (Pisa UI) not trusting CERN, indeed urllib does not accept a `capath` argument the way it takes cert and key, and the way we use it in curl.

Indeed, using curl from Pisa UI in CLI mode, it is cleat that the system default does not trust CERN:

```
[belforte@gridui3 ~]$ curl -o /dev/null --cert $X509_USER_PROXY --key $X509_USER_PROXY  https://cmsweb.cern.ch/scheddmon/0119/cms574/170509_212924:santocch_crab_MET_E/status_cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[belforte@gridui3 ~]$ 
```

while adding explicitely the capath:
```
[belforte@gridui3 ~]$ curl -o /dev/null --cert $X509_USER_PROXY --key $X509_USER_PROXY --capath /etc/grid-security/certificates  https://cmsweb.cern.ch/scheddmon/0119/cms574/170509_212924:santocch_crab_MET_E/status_cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  497k  100  497k    0     0   644k      0 --:--:-- --:--:-- --:--:--  645k
[belforte@gridui3 ~]$ 
```

while on most "more carefully configured UI's" like lxplus
```
belforte@lxplus049/TC3> curl -o /dev/null --cert $X509_USER_PROXY --key $X509_USER_PROXY  https://cmsweb.cern.ch/scheddmon/0119/cms574/170509_212924:santocch_crab_MET_E/status_cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  497k  100  497k    0     0   772k      0 --:--:-- --:--:-- --:--:--  792k
belforte@lxplus049/TC3> 
```

everytime I use the `curl` which comes with CMSSW since the system one does not support SSL

I am not surprised that Attilio could retrieve the status_cache via the browser since the CERN root CA is usually esplicitely uploaded and trusted in the browsers anyhow.
But at this point I am puzzled as to how the CRAB client can connect to CRAB REST on cmsweb !



If anything I am curious how CRAB client can connect to CRAB REST on cmsweb.
I am not surp

**Comment by belforte** [comment]
OK. When client connects to CRAB server REST this saves it:
https://github.com/dmwm/CRABServer/blob/3.3.1705.rc3/src/python/RESTInteractions.py#L165-L177

I have still not found how cliebt manages to properly configure when e.g. using pycurl to communcate with UFC. But I cant' find other cases where client uses pycurl.
So maybe using RESTInteractions also to download status_cache is an attractive option

**Comment by belforte** [comment]
In any case, should the downloading of the cache file fail for any reason, client should not simply print
```
Waiting for the Grid scheduler to report back the status of your task
```
There should be a clear error indication and the exception found in crab.log shold be reported on the stdout. That will save time in handling problem reports.
