### ISSUE TITLE
getlog --short fails with ERROR: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4803]
crab client log:
```
DEBUG 2019-03-19 17:03:36,287: 	 Options use: ['--short', '--jobid=1', '-d', 'crab_20190319_103049/']
INFO 2019-03-19 17:03:36,401: 	 Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1902.rc1']
DEBUG 2019-03-19 17:03:36,401: 	 Instance is prod
DEBUG 2019-03-19 17:03:36,401: 	 Server base url is cmsweb.cern.ch
DEBUG 2019-03-19 17:03:36,401: 	 Command url /crabserver/prod/workflow
INFO 2019-03-19 17:03:36,485: 	 Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/mio/crab_20190319_103049/results 
INFO 2019-03-19 17:03:36,485: 	 Retrieving...
ERROR 2019-03-19 17:03:36,490: 	 Unhandled Exception!
ERROR 2019-03-19 17:03:36,490: 	 need more than 1 value to unpack
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 160, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 148, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 42, in __call__
    failed, success = self.retrieveShortLogs(webdir, self.proxyfilename)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 98, in retrieveShortLogs
    for _, jobid in self.options.jobids:
ValueError: need more than 1 value to unpack
ERROR 2019-03-19 17:03:36,558: 	 ERROR: ValueError: need more than 1 value to unpack

```

Looking at the code it seems broken since ~ever  in
https://github.com/dmwm/CRABClient/blob/6a03ba37b3c22644ff9d82a09448a2faf0dab86f/src/python/CRABClient/Commands/getlog.py#L98
since `options.jobids` is a simple list with a single value for each item.

I have no idea if earlier jobids was a different structure, already previous version of getlog indicates a two value list for each jobid item:
https://github.com/dmwm/CRABClient/commit/3bbc51c7448dc077b4b8cd26c0191114d79dc8de

Maybe it has broken forever ?

**Comment by belforte** [comment]
`self.options.jobids` is not a list of values. But it is apparently imported as a string as it appears in the commad:
```
(Pdb) self.options.jobids
'10,11,12,13,14,15,16,17,18,19,20'
```

Given how many commands support jobdis, there should be a central place where that is parsed into a list of  jobids. I will look for that before writing my own.
