### ISSUE TITLE
defaul value for config.General.instance is lost

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4838]
crab submit report failure with the following traceback, but actually submits !

```
ERROR 2019-10-22 02:48:19.659 UTC: 	 Unhandled Exception!
ERROR 2019-10-22 02:48:19.659 UTC: 	 'ConfigSection' object has no attribute 'instance'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc7_amd64_gcc630/cms/crabclient/3.3.1910.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc7_amd64_gcc630/cms/crabclient/3.3.1910.patch1/bin/crab", line 147, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/crab3/slc7_amd64_gcc630/cms/crabclient/3.3.1910.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 144, in __call__
    self.logger.info("%sSuccess%s: Your task has been delivered to the %s CRAB3 server." % (colors.GREEN, colors.NORMAL, self.configuration.General.instance))
AttributeError: 'ConfigSection' object has no attribute 'instance'
ERROR 2019-10-22 02:48:19.660 UTC: 	 ERROR: AttributeError: 'ConfigSection' object has no attribute 'instance'
ERROR 2019-10-22 02:48:19.660 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2019-10-22 02:48:19.660 UTC: 	 	Client Version: 3.3.1910.patch1

```

**Comment by belforte** [comment]
in other words, the error occurs when the client tries to print the name of the crab server it submitted to, but the previous submission was fine
