### ISSUE TITLE
Add host name to crab.log file when there's an http error

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#4884]
```
[ddirmait@lxplus780` crab_20200218_184820]$ less crab.log 
 error: 
 retcode : 0
DEBUG 2020-02-18 17:48:21.277 UTC:       Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93401 -actimeleft
 output : 603008

 error: 
 retcode : 0
DEBUG 2020-02-18 17:48:21.277 UTC:       Proxy lifetime 603009 secs is different from voms extension lifetime 603008 secs for proxy: /tmp/x509up_u93401
DEBUG 2020-02-18 17:48:21.277 UTC:       Proxy valid for 167:30:08 hours
DEBUG 2020-02-18 17:48:21.782 UTC:       Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u93401 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2020-02-18 17:48:21.793 UTC:       (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')
ERROR 2020-02-18 17:48:21.793 UTC:       Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 359, in __init__
    self.handleProxy(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 437, in handleProxy
    all_task_workers_dns = server_info('delegatedn', self.serverurl, self.proxyfilename, baseurl)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 799, in server_info
    dictresult, dummyStatus, dummyReason = server.get(baseurl, requestdict)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/RESTInteractions.py", line 79, in get
    return self.makeRequest(uri = uri, data = data, verb = 'GET')
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/RESTInteractions.py", line 129, in makeRequest
    verbose=self['verbose'])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 257, in request
    curl.perform()
error: (35, 'error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version')
INFO 2020-02-18 17:48:21.793 UTC:        It seems the CMSWEB frontend is not responding. Please check: https://twiki.cern.ch/twiki/bin/viewauth/CMS/ScheduledInterventions?sortcol=3;table=1;up=2#sorted_table
```

**Comment by belforte** [comment]
http calls are handled via
https://github.com/dmwm/CRABServer/blob/e65c5e83c3f8974bee9b0cbd2cfa8d60ba0b1ce6/src/python/RESTInteractions.py#L34
So I make an issue in CrabServer as well:
https://github.com/dmwm/CRABServer/issues/6019

**Comment by belforte** [comment]
code in my branch now produces e.g. this output when a nonexistiing REST host name is used in config:
```
belforte@lxplus704/LOCAL> crab submit 
Will use CRAB configuration file crabConfig.py
Fatal error trying to connect to https://nowhere.cern.ch
(6, 'Could not resolve host: nowhere.cern.ch')
It seems the CMSWEB frontend is not responding. Please check: https://twiki.cern.ch/twiki/bin/viewauth/CMS/ScheduledInterventions?sortcol=3;table=1;up=2#sorted_table
belforte@lxplus704/LOCAL> 
```

**Comment by belforte** [comment]
I guess I want to log the full URL, not only the host name. Try more..

**Comment by belforte** [comment]
done. Final version prints
```
belforte@lxplus704/LOCAL> crab submit 
Will use CRAB configuration file crabConfig.py
Fatal error trying to connect to https://nowhere.cern.ch using {'baserul': '/crabserver/dev/info', 'subresource': 'delegatedn'}
(6, 'Could not resolve host: nowhere.cern.ch')
It seems the CMSWEB frontend is not responding. Please check: https://twiki.cern.ch/twiki/bin/viewauth/CMS/ScheduledInterventions?sortcol=3;table=1;up=2#sorted_table
belforte@lxplus704/LOCAL> 
```

**Comment by belforte** [comment]
did something wrong, it does not work with correct config.

**Comment by belforte** [comment]
this should have solved
https://github.com/belforte/CRABClient/commit/79d343a97a033b1a7e831d2e1433ef7b65457218

**Comment by belforte** [comment]
now up to date in master head. WIll tag after more testing
- [ ] will also need a new CRABServer tag in order to build the client on CVMFS

**Comment by belforte** [comment]
done in CRAB Client 3.3.2003.rc1 and tested as crab-dev in nightly IB
https://cms-logbook.cern.ch/elog/Analysis+Operations/2957
