### ISSUE TITLE
make CRABClient python3 compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4925]
first step in making all of CRAB to be so.
Since client depends "only" on CMSSW, which is python3 capable, should be reasonably easy.

After https://github.com/dmwm/CRABClient/issues/4923
the next obstacle is
```
belforte@lxplus714/CRABClient> python3 bin/crab          
Traceback (most recent call last):
  File "bin/crab", line 27, in <module>
    from ServerUtilities import FEEDBACKMAIL
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/ServerUtilities.py", line 90, in <module>
    TRANSFERDB_STATUSES = dict((v, k) for k, v in TRANSFERDB_STATES.iteritems())
AttributeError: 'dict' object has no attribute 'iteritems'
belforte@lxplus714/CRABClient> 
```

which we already knew about a couple years ago, but at the time Eric told us to wait to address it "at the time we actually migrate".
Here's a couple pointers
https://www.python.org/dev/peps/pep-0469/
https://stackoverflow.com/a/13998541/13696042

I suspect we do not care in here about possibly loosing some performance and could go straight for replacing `iteritems` with `items`
Anyhow needs to be tested.

Then there may be other things. Besides the fact that functions we use from CRABServer and WMCore need to be made python3 compatible.

**Comment by belforte** [comment]
breakdown into actions
- [ ] fix usage of `iteritems()` in CRABClient code
- [ ] fix import of HTTException in CRABServer https://github.com/dmwm/CRABServer/issues/6092
- [ ] fix import of HTTException in WMCore as needed
- [ ] fix usage of `iteritems()` in CRABServer as needed for this (only two files !)
- [ ]  fix usage of `iteritems()` in WMCore as needed

**Comment by belforte** [comment]
more issues:
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 15, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```
most likely simply `import pickle` will do, and if it is a bit slower on python2, so be it. See
https://stackoverflow.com/a/37138791/13696042

**Comment by belforte** [comment]
Next
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 18, in <module>
    from string import upper
ImportError: cannot import name 'upper'
```
I start to suspect that pylint python3 compatibiliyt check have not been run on CRAB Client.  How can it have missed so many simple things ?

**Comment by belforte** [comment]
next:
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 19, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by belforte** [comment]
next:
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/WMException.py", line 9, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
```
this can be solved via '`six'  as
```
import six
if six.PY2:
    from exceptions import Exception
class WMException(Exception):

```

**Comment by belforte** [comment]
next:
```
File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/DataStructs/LumiList.py", line 20, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```
here could do
```
from six.moves.urllib.error import HTTPError
```
from https://python-future.org/compatible_idioms.html

**Comment by belforte** [comment]
next
```
 File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 41, in <module>
    import cStringIO as StringIO
ModuleNotFoundError: No module named 'cStringIO'
```
solution from https://python-future.org/compatible_idioms.html
```
from io import StringIO    # for handling unicode strings
```

**Comment by belforte** [comment]
next
```
  File "bin/crab", line 208, in <module>
    except StopExecution:
TypeError: catching classes that do not inherit from BaseException is not allowed
```
comes from
https://github.com/dmwm/CRABClient/blob/cde999e656e44f3cbfb3f1067a98324405519c9f/src/python/CRABClient/ClientUtilities.py#L58

**Comment by belforte** [comment]
after all that
```
belforte@lxplus714/CRABClient> python3 bin/crab 
You have not specified a command.

Valid commands are: 
  checkusername
  checkwrite (chk)
  getlog (log)
  getoutput (output) (out)
  kill
  preparelocal
  proceed
  purge
  remake (rmk)
  report (rep)
  resubmit
  status (st)
  submit (sub)
  tasks
  uploadlog (uplog)
To get single command help run:
  crab command --help|-h

For more information on how to run CRAB-3 please follow this link:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCRAB3Tutorial

belforte@lxplus714/CRABClient> python3 bin/crab --version
CRAB client development
belforte@lxplus714/CRABClient> 
```

full validation will of course be needed.  etc. etc.

**Comment by belforte** [comment]
list of WMCore files which I modified:
```
belforte@lxplus714/WMCore> git status
HEAD detached at 1.3.3
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/python/WMCore/Configuration.py
	modified:   src/python/WMCore/DataStructs/LumiList.py
	modified:   src/python/WMCore/Services/Requests.py
	modified:   src/python/WMCore/Services/Service.py
	modified:   src/python/WMCore/Services/pycurl_manager.py
	modified:   src/python/WMCore/WMException.py

```

**Comment by belforte** [comment]
list of CRABClient files which I modified:

```
belforte@lxplus714/CRABClient> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bin/crab
	modified:   src/python/CRABClient/ClientMapping.py
	modified:   src/python/CRABClient/ClientUtilities.py
	modified:   src/python/CRABClient/Commands/checkwrite.py
	modified:   src/python/CRABClient/Commands/getlog.py
	modified:   src/python/CRABClient/Commands/kill.py
	modified:   src/python/CRABClient/Commands/purge.py
	modified:   src/python/CRABClient/Commands/report.py
	modified:   src/python/CRABClient/Commands/status.py
	modified:   src/python/CRABClient/Commands/submit.py
	modified:   src/python/CRABClient/JobType/Analysis.py
	modified:   src/python/CRABClient/JobType/CopyCat.py
	modified:   src/python/CRABClient/JobType/LumiMask.py
	modified:   src/python/CRABClient/UserUtilities.py

```

**Comment by belforte** [comment]
I also had to modify the files imported from CRABServer
```
	src/python/RESTInteractions.py
	src/python/ServerUtilities.py
```

**Comment by belforte** [comment]
needed changes in CRABServer https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649948827 are now in https://github.com/belforte/CRABServer/tree/py3-for-CrabClient

**Comment by belforte** [comment]
how to test (from Shahzad) :

1. python3 crab
2. using CMSSW_11_2_PY3_X based IBs where python defaults to python3

**Comment by belforte** [comment]
python3 is very fussy about syntax warning which python2 overlooked
```
belforte@lxplus714/LOCAL> crab status
/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py:405: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if instance is not 'other':
ERROR: TypeError: a bytes-like object is required, not 'str'
```
need to get pylint to run on CRABClient and make sure we find and address all such things

@ddaina can you look into making Jenkins run same tests it runs on CRABServer also on CRABClient ?
and make sure pylint flags issues like this before we found them run time ? I'd rather not grep all the code base for "is" or "is not" !

**Comment by belforte** [comment]
more syntax complains. This one I do not know how to solve yet
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 228, in __init__
    localSystem = subprocess.check_output(['uname', '-a']).strip('\n')
TypeError: a bytes-like object is required, not 'str'
ERROR 2020-06-26 05:32:00.292 UTC: 	 ERROR: TypeError: a bytes-like object is required, not 'str'
```
ref. https://stackoverflow.com/questions/44989808/subprocess-typeerror-a-bytes-like-object-is-required-not-str

**Comment by belforte** [comment]
more issues I found
* https://stackoverflow.com/questions/39146039/pickle-typeerror-a-bytes-like-object-is-required-not-str (in ClientUtilities)
* `ERROR: AttributeError: module 'urllib' has no attribute 'quote'` in RESTInteractions.py from CRABServer

**Comment by belforte** [comment]
and finally I have some big mess with pycurl which I can't solve with the kick-after-kick approach used so far:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 128, in makeRequest
    response, datares = self['conn'].request(url, data, encode=True, headers=headers, verb=verb, doseq = True,
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 258, in request
    curl.perform()
pycurl.error: (23, 'Failed writing header')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 165, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 365, in __init__
    self.handleProxy(proxyOptsSetPlace)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 451, in handleProxy
    all_task_workers_dns = server_info(subresource='delegatedn', serverurl=self.serverurl,
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 663, in server_info
    dictresult, dummyStatus, dummyReason = server.get(baseurl, requestdict)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 79, in get
    return self.makeRequest(uri = uri, data = data, verb = 'GET')
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 133, in makeRequest
    if (not retriableError(ex)) or (i == self['retry']):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 30, in retriableError
    return ex[0] in [28, 35]
TypeError: 'error' object is not subscriptable

```

**Comment by belforte** [comment]
putting in Hold. Wil get back to this when have more time and once WMCore base classes like `pycurl_maanger` have been validated by WMCore team first

**Comment by belforte** [comment]
`crab submit` fails at
```
belforte@lxplus714/LOCAL> crab submit 
Will use CRAB configuration file crabConfig.py
Invalid type StringType specified in CRABClient configuration mapping for parameter General.requestName.
```

**Comment by belforte** [comment]
as per discussion with Alan, Eric and DaviL. should minimize use of six

**Comment by belforte** [comment]
See also this thread with Alan and Dario

**Comment by belforte** [comment]
and this one

**Comment by ddaina** [comment]
@belforte, you asked me to _["<...>look into making Jenkins run same tests it runs on CRABServer also on CRABServer?"](https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649977976)_ - I've overlooked this request, but I can confirm that Jenkins runs the same pylint test for both CRABServer and CRABServer. But since those tests were broken for quite a while (year or so) so most probably those pylint errors were introduced in the meantime or before tests were put in place. For instance, we can take this [PR](https://github.com/dmwm/CRABClient/pull/4813 ) from Jun 21, 2019 where pylint report was produced.

**Comment by belforte** [comment]
thanks @ddaina    It is good that Jenkins now run on both repos with same tests, but the question still is "does it catch issues like this https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649977976 ?" 

and once we are sure that it does, how can we make it run on the full repository so to check all files, not only the ones modified in a PR ?  Well.. for doing it "once as a bootstrap", I am also happy to do it manually as long as we have the correct pylint config.

**Comment by ddaina** [comment]
> thanks @ddaina It is good that Jenkins now run on both repos with same tests, but the question still is "does it catch issues like this [#4925 (comment)](https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649977976) ?"
> 
I ran pylint test using current pylintrc used for CRAB testing and that issue was captured. 

> and once we are sure that it does, how can we make it run on the full repository so to check all files, not only the ones modified in a PR ? Well.. for doing it "once as a bootstrap", I am also happy to do it manually as long as we have the correct pylint config.
> 

I'll have a look and come back to this

> Well.. we better follow up on this Jenkins topic off this issue !

agree

**Comment by belforte** [comment]
just tried the old python3 branch which I created in June 2020 with many of the fixes for the issues above 
https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649808464
and recent py23 compatible WMCore 1.4.6 which now should solve problems with pycurl, pickle etc. on the
current PY3 only release  CMSSW_11_3_0_pre2_PY3 and after quickly fixing on the fly the two files imported from CRABServer (ServerUtilities and RESTInterface) I got `crab --version` and `crab --help` to work but
immediately hit again the `str vs byte thing`
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 228, in __init__
    localSystem = subprocess.check_output(['uname', '-a']).strip('\n')
TypeError: a bytes-like object is required, not 'str'
ERROR 2021-03-10 16:24:23.192 UTC: 	 ERROR: TypeError: a bytes-like object is required, not 'str'
```
So no command can work. And even hacking around that I get
```
ERROR 2021-03-10 16:44:17.670 UTC: 	 ERROR: TypeError: can only concatenate str (not "bytes") to str
```

As stated [then](https://github.com/dmwm/CRABClient/issues/4925#issuecomment-649981452) a global approach is needed. We should also look into not using `six` and make more use of the same tricks Dario used in WMCore for py2-3 compatibility.
