### ISSUE TITLE
crab report - IndexError: list index out of range

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4939]
The user reported it as a transient error.

Task URL:
https://cmsweb.cern.ch/crabserver/ui/task/200812_120954%3Amgadalla_crab_CMSDAS_Data_analysis_test01

From the attached [CRAB log:](https://github.com/dmwm/CRABClient/files/5067939/200812_120954-mgadalla_crab_CMSDAS_Data_analysis_test01.log)

```
ERROR 2020-08-12 14:00:50.931 UTC: 	 Unhandled Exception!
ERROR 2020-08-12 14:00:50.931 UTC: 	 list index out of range
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/bin/crab", line 152, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/lib/CRABClient/Commands/report.py", line 40, in __call__
    reportData = self.collectReportData()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/lib/CRABClient/Commands/report.py", line 333, in collectReportData
    repDGO = self.getDBSPublicationInfo_viaDasGoclient(reportData['outputDatasets'])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/lib/CRABClient/Commands/report.py", line 466, in getDBSPublicationInfo_viaDasGoclient
    total_events = result[0]['summary'][0]['nevents']
IndexError: list index out of range
ERROR 2020-08-12 14:00:50.933 UTC: 	 ERROR: IndexError: list index out of range
```

**Comment by belforte** [comment]
Thanks @lecriste Most likely I need to better handle cases when dasgoclient does not return useful info, usually when DBS is down or overloaded
