### ISSUE TITLE
Make CreateProxy part of the distribuion

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4949]

**Comment by belforte** [comment]
```

Well... on the good side I understand this now. On the less so good I am not sure
how best to solve. We need to keep the ability to modify code, and what I did this time
was to make sure that changes elsewhere were also propagate in CreateProxy.py for
a consistent set of code.
The problem is that the say Shahzad magic works, crab command points to prod, crab-dev to dev etc.
all conistently, but we do not "distribute" CreateProxy with that, so you pull it from github
and get the most recent, i.e. development copy. And are even in danger of downloading
a broken version if you do it while I hack around.

I need to find a permanent solution, ideally where you do not pull things from github,
but where the CreateProxy is part of the environment created by source /cvmfs/cms.cern.ch/common/crab-setup.sh

Stefano

On 02/11/2020 11:10, Andrea Sciabà wrote:
> You did it!
>
> [asciaba@lxplus7111 ~]$ myproxy-info -s myproxy.cern.ch -l sciaba_CRAB
> username: sciaba_CRAB
> owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba
>    renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
>    trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
>    timeleft: 2399:59:38  (100.0 days)
>
>      Andrea
>
> On 2020-11-02 11:07, Stefano Belforte wrote:
>> Andrea, pleaset try:
>> source /cvmfs/cms.cern.ch/common/crab-setup.sh dev
>> ./CreateProxy.py.1 -r production -s cmsweb.cern.ch -u /crabserver/prod/info -d 100
>>
>> i.e. use dev version of CRAB.
>> I am trying to find out exectly where I failed to keep consistency across versions.
>>
>> Stefano
>>
>> On 02/11/2020 10:53, Stefano Belforte wrote:
>>> Problem confirmed. I need to figure out details and fix. Sorry
>>> Andrea, if you can do a simple crab submit, with any config. it
>>> will delegate the needed credential, simply will only last 15 days
>>> insteacd of 3 months. I will fix CreateProxy in the meanwhile.
>>> Stefano
>>>
>>> On 02/11/2020 10:46, Stefano Belforte wrote:
>>>> oh my... did I screw up something again ?
>>>>
>>>>
>>>> On 02/11/2020 10:34, Andrea Sciabà wrote:
>>>>> I tried with the latest CreateProxy.py and I got this error:
>>>>>
>>>>> -bash-4.2$ ./CreateProxy.py.1 -r production -s cmsweb.cern.ch -u /crabserver/prod/info -d 100
>>>>> Traceback (most recent call last):
>>>>>    File "./CreateProxy.py.1", line 91, in <module>
>>>>>      handleProxy( options.server, options.url, options.role, options.group, options.days )
>>>>>    File "./CreateProxy.py.1", line 50, in handleProxy
>>>>>      proxy = CredentialInteractions('', '', voRole, voGroup, logging)
>>>>> TypeError: __init__() takes exactly 7 arguments (6 given)
>>>>>
>>>>>
>>>>> Did something change in the CredentialInteractions implementation?
>>>>>
>>>>>      Andrea
>>>>>
>>>>>
>>>>> On 2020-11-02 10:27, Andrea Sciabà wrote:
>>>>>> I just re-ran the commands and the time left for sciaba_CRAB is still zero.
>>>>>>
>>>>>>      Andrea
>>>>>>
>>>>>> On 2020-11-02 10:22, Andrea Sciabà wrote:
>>>>>>> Hi all,
>>>>>>>
>>>>>>> I don't have any valid long term proxy called sciaba_CRAB:
>>>>>>>
>>>>>>> -bash-4.2$ myproxy-info -s myproxy.cern.ch -l sciaba_CRAB
>>>>>>> username: sciaba_CRAB
>>>>>>> owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba
>>>>>>>    renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
>>>>>>>    trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
>>>>>>>    timeleft: 0:00:00
>>>>>>>
>>>>>>>
>>>>>>> I had renewed proxy and delegation like I always did in the past, by doing:
>>>>>>>
>>>>>>> source /cvmfs/cms.cern.ch/common/crab-setup.sh
>>>>>>> cd CMSSW_10_6_1
>>>>>>> cmsenv
>>>>>>> cd ..
>>>>>>> ./CreateProxy.py -r production -s cmsweb.cern.ch -u /crabserver/prod/info -d 100
>>>>>>> export GT_PROXY_MODE="old"
>>>>>>> myproxy-init -d -n -s myproxy.cern.ch -x -Z "/DC=ch/DC=cern/OU=computers/CN=hammercloud-ai-[0-9][0-9].cern.ch" -k HammerCloudpattern -t 168:00 -c 4500 -l sciabahc
>>>>>>>
>>>>>>> The client I'm using is new, but I see that it's not the latest, and the diff is simply:
>>>>>>>
>>>>>>> -bash-4.2$ diff CreateProxy.py CreateProxy.py.1
>>>>>>> 50c50
>>>>>>> <     proxy = CredentialInteractions('', '', voRole, voGroup, logging, myproxyAccount=server)
>>>>>>> ---
>>>>>>>  >     proxy = CredentialInteractions('', '', voRole, voGroup, logging)
>>>>>>> 66a67
>>>>>>>  >         proxy.createNewMyProxy2( timeleftthreshold = 60 * 60 * 24 * RENEW_MYPROXY_THRESHOLD, nokey=True)
>>>>>>>
>>>>>>> I don't know if this might be the problem.
>>>>>>>
>>>>>>>      Andrea
>>>>>>>
>>>>>>>
>>>>>>> On 2020-10-31 14:31, Stefano Belforte wrote:
>>>>>>>> hmm... still fails
>>>>>>>> 2020-10-31 14:25:59,093:DEBUG:Proxy:using sciaba_CRAB as credential login name
>>>>>>>> 2020-10-31 14:25:59,329:DEBUG:Proxy:Executing :
>>>>>>>>   command : env -i sh -c 'unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/hostcert.pem X509_USER_KE
>>>>>>>> Y=/data/certs/hostkey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/db85de4154ab6954b8b313bee9b264083
>>>>>>>> 57e57f4.25074 -l "sciaba_CRAB" -t 168:00'
>>>>>>>>   output :
>>>>>>>>   error: Failed to receive credentials.
>>>>>>>> ERROR from myproxy-server:
>>>>>>>> X509_verify_cert() failed: certificate has expired
>>>>>>>>
>>>>>>>>   retcode : 1
>>>>>>>>
>>>>>>>>
>>>>>>>> Andrea can you check with:
>>>>>>>> myproxy-info -s myproxy.cern.ch -l sciaba_CRAB
>>>>>>>> ?
>>>>>>>>
>>>>>>>> Maybe you are using an old version of the client (i.e. the CreateProxy script ?
>>>>>>>> You should use this one:
>>>>>>>> https://github.com/dmwm/CRABClient/blob/master/bin/CreateProxy.py
>>>>>>>>
>>>>>>>> thanks
>>>>>>>> Stefano
>>>>>>>>
>>>>>>>> On 31/10/2020 14:15, Stefano Belforte wrote:
>>>>>>>>> indeed the error was:
>>>>>>>>>   command : env -i sh -c 'unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/hostcert.pem X509_USER_KE
>>>>>>>>> Y=/data/certs/hostkey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/db85de4154ab6954b8b313bee9b264083
>>>>>>>>> 57e57f4.25072 -l "sciaba_CRAB" -t 168:00'
>>>>>>>>>   output :
>>>>>>>>>   error: Failed to receive credentials.
>>>>>>>>> ERROR from myproxy-server:
>>>>>>>>> X509_verify_cert() failed: certificate has expired
>>>>>>>>>
>>>>>>>>> let's see how next submissions fare
>>>>>>>>> Stefano
>>>>>>>>>
>>>>>>>>> On 31/10/2020 14:12, Andrea Sciaba wrote:
>>>>>>>>>> Done!
>>>>>>>>>>
>>>>>>>>>> Sent from Mail <https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
>>>>>>>>>>
>>>>>>>>>> *From: *Jaroslava Schovancova <mailto:Jaroslava.Schovancova@cern.ch>
>>>>>>>>>> *Sent: *sabato 31 ottobre 2020 11:48
>>>>>>>>>> *To: *Stefano Belforte <mailto:Stefano.Belforte@cern.ch>; Andrea Sciaba <mailto:Andrea.Sciaba@cern.ch>
>>>>>>>>>> *Cc: *Prajesh Sharma <mailto:prajesh.sharma@cern.ch>; Daina Dirmaite <mailto:daina.dirmaite@cern.ch>
>>>>>>>>>> *Subject: *Re: Possible certificate expired for CMS CRAB3 (or infrastructure behind)?
>>>>>>>>>>
>>>>>>>>>> Dear Stefano, Daina and Prajesh,
>>>>>>>>>> nice to meet you, at least in this remote way!
>>>>>>>>>>
>>>>>>>>>> Stefano, we noticed notifications overnight with lack of jobs in golden
>>>>>>>>>> tests, I was going to check further.
>>>>>>>>>> There was no change on the HC side.
>>>>>>>>>>
>>>>>>>>>> Unfortunately, only Andrea can re-delegate to myproxy -- Andrea, could
>>>>>>>>>> you please have a look whenever you are back to keyboard?
>>>>>>>>>>
>>>>>>>>>> Many thanks, cheers,
>>>>>>>>>> Jarka
>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>> On 10/31/20 11:23 AM, Stefano Belforte wrote:
>>>>>>>>>>> Dear Jarka,
>>>>>>>>>>> let me introduce you to CRAB operators Daina and Prajesh, and viceversa.
>>>>>>>>>>>
>>>>>>>>>>> Prajesh noticed that we have a flood of HC submission failure
>>>>>>>>>>> starting last night at 10pm with
>>>>>>>>>>> Impossible to retrieve proxy from myproxy.cern.ch for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba."
>>>>>>>>>>>
>>>>>>>>>>> We have not changed anything on our side, did you ?
>>>>>>>>>>> Can you simply renew the credentails in myproxy, just in case ?
>>>>>>>>>>>
>>>>>>>>>>> Thanks
>>>>>>>>>>> Stefano
>>>>>>>>>>>
>>>>>>>>>>> On 30/10/2020 14:43, Jaroslava Schovancova wrote:
>>>>>>>>>>>> Dear All,
>>>>>>>>>>>> many thanks for having a look!
>>>>>>>>>>>> Apologies for the spam -- it was indeed a proxy file with wrong permission (owned by another local user).
>>>>>>>>>>>>
>>>>>>>>>>>> Stay safe & bon weekend!
>>>>>>>>>>>> Cheers, Jarka
>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>> On 10/30/20 12:38 PM, Marco Mascheroni wrote:
>>>>>>>>>>>>> Thanks Stefano,
>>>>>>>>>>>>>
>>>>>>>>>>>>> I recognized this error message https://github.com/dmwm/CRABServer/blob/master/src/python/RESTInteractions.py#L137
>>>>>>>>>>>>> and for some reason I thought we were using the library on the CRAB Server. But indeed it is something we use in the CRAB client.
>>>>>>>>>>>>>
>>>>>>>>>>>>> Jarka, seems to me that what is expired is the "user proxy" that HC uses to connect to the CRAB server.
>>>>>>>>>>>>>
>>>>>>>>>>>>> On Fri, Oct 30, 2020 at 11:40 AM Stefano Belforte <stefano.belforte@cern.ch <mailto:stefano.belforte@cern.ch>> wrote:
>>>>>>>>>>>>>
>>>>>>>>>>>>>     Anyhow CRAB infrastructure is working, no sign of any certificate issues
>>>>>>>>>>>>>
>>>>>>>>>>>>>     On 30/10/2020 11:38, Stefano Belforte wrote:
>>>>>>>>>>>>>     > that must refer to some HC internals.
>>>>>>>>>>>>>     > Jarka, can you log in one HC host and try a simple crab submit manually ?
>>>>>>>>>>>>>     > SSL error messages are really hateful, they never say at which end of the
>>>>>>>>>>>>>     > communication the error is !
>>>>>>>>>>>>>     >
>>>>>>>>>>>>>     > On 30/10/2020 11:26, Marco Mascheroni wrote:
>>>>>>>>>>>>>     >> Ciao Andrea,
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >> Jarka, what is the hostname of the crabserver you are using? Also, I can't really tell what is thisForkPoolWorker (from DEBUG/ForkPoolWorker-3][CRAB3.all:142]), let's ask Stefano.
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >> Cheers,
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >> Marco Mascheroni
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >> On Fri, Oct 30, 2020 at 11:14 AM Andrea Sciaba <Andrea.Sciaba@cern.ch <mailto:Andrea.Sciaba@cern.ch>
>>>>>>>>>>>>> <mailto:Andrea.Sciaba@cern.ch <mailto:Andrea.Sciaba@cern.ch>>> wrote:
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     Hi Jarka,
>>>>>>>>>>>>>     >>     Right now I can't check, I'm on leave and outdoors. Marco, could it be what Jarka suggests?
>>>>>>>>>>>>>     >>     Cheers,
>>>>>>>>>>>>>     >>     Andrea
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     On Oct 30, 2020 10:19, Jaroslava Schovancova <Jaroslava.Schovancova@cern.ch <mailto:Jaroslava.Schovancova@cern.ch>
>>>>>>>>>>>>> <mailto:Jaroslava.Schovancova@cern.ch
>>>>>>>>>>>>> <mailto:Jaroslava.Schovancova@cern.ch>>> wrote:
>>>>>>>>>>>>>     >>     Ciao Andrea,
>>>>>>>>>>>>>     >>     I'm restarting CMS celerization / decommissioning of the SLC6
>>>>>>>>>>>>>     >>     infrastructure, and I'm getting error
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     [2020-10-30 10:16:51,699: DEBUG/ForkPoolWorker-3][CRAB3.all:142]
>>>>>>>>>>>>>     >>     Sleeping 20 seconds after HTTP error. Error details: (35,
>>>>>>>>>>>>>     >>     'error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate
>>>>>>>>>>>>>     >>     expired')
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     Is it possible that some host certificate expired on CRAB3 servers / CMS
>>>>>>>>>>>>>     >>     webserver used by CRAB3?
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     This is for test [1], more details e.g. [2].
>>>>>>>>>>>>>     >>     I checked HC nodes, host certificates are fine (from May / August this
>>>>>>>>>>>>>     >>     year).
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     Thank you, cheers,
>>>>>>>>>>>>>     >>     Jarka
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     [1] http://hammercloud.cern.ch/hc/app/cms/test/93401/
>>>>>>>>>>>>>     >>     [2]
>>>>>>>>>>>>>     >>     s.celery']
>>>>>>>>>>>>>     >>     [2020-10-30 10:18:32,560: INFO/ForkPoolWorker-2][cms.celery.crab:144]
>>>>>>>>>>>>>     >>     :122a configurationCache: {}
>>>>>>>>>>>>>     >>     [2020-10-30 10:18:32,565: INFO/ForkPoolWorker-2][cms.celery.crab:148]
>>>>>>>>>>>>>     >>     :123 crab_config: from WMCore.Configuration import Configuration
>>>>>>>>>>>>>     >>     config = Configuration()
>>>>>>>>>>>>>     >>     config.section_('User')
>>>>>>>>>>>>>     >>     config.User.voRole = 'production'
>>>>>>>>>>>>>     >>     config.section_('JobType')
>>>>>>>>>>>>>     >>     config.JobType.allowUndistributedCMSSW = True
>>>>>>>>>>>>>     >>     config.JobType.priority = 600000
>>>>>>>>>>>>>     >>     config.JobType.psetName =
>>>>>>>>>>>>>     >> '/data/hc/apps/cms/inputfiles/usercode/miniaodsim_9xx.py'
>>>>>>>>>>>>>     >>     config.JobType.pluginName = 'Analysis'
>>>>>>>>>>>>>     >>     config.JobType.maxJobRuntimeMin = 300
>>>>>>>>>>>>>     >>     config.section_('Data')
>>>>>>>>>>>>>     >>     config.Data.publication = False
>>>>>>>>>>>>>     >>     config.Data.unitsPerJob = 15
>>>>>>>>>>>>>     >>     config.Data.splitting = 'LumiBased'
>>>>>>>>>>>>>     >>     config.Data.outputDatasetTag = '0ea12bcd230936c2556840cb8452714d'
>>>>>>>>>>>>>     >>     config.Data.inputDataset =
>>>>>>>>>>>>>     >> '/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM'
>>>>>>>>>>>>>     >>     config.Data.totalUnits = 3315
>>>>>>>>>>>>>     >>     config.Data.allowNonValidInputDataset = True
>>>>>>>>>>>>>     >>     config.Data.ignoreLocality = True
>>>>>>>>>>>>>     >>     config.section_('Debug')
>>>>>>>>>>>>>     >>     config.Debug.extraJDL = ['+CRAB_NoWNStageout=1']
>>>>>>>>>>>>>     >>     config.section_('Site')
>>>>>>>>>>>>>     >>     config.Site.storageSite = 'T2_CH_CERN'
>>>>>>>>>>>>>     >>     config.Site.blacklist = ['T3*']
>>>>>>>>>>>>>     >>     config.Site.whitelist = ['T2_RU_JINR']
>>>>>>>>>>>>>     >>     config.section_('General')
>>>>>>>>>>>>>     >>     config.General.transferLogs = False
>>>>>>>>>>>>>     >>     config.General.requestName = 'HC-203-T2_RU_JINR-92236-20200810032904'
>>>>>>>>>>>>>     >>     config.General.transferOutputs = False
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>     >>     --     Jaroslava Schovancová
>>>>>>>>>>>>>     >>     CERN IT-CM-IS
>>>>>>>>>>>>>     >>     +41754118301 (16-8301)
>>>>>>>>>>>>>     >> Jaroslava.Schovancova@cern.ch <mailto:Jaroslava.Schovancova@cern.ch>
>>>>>>>>>>>>> <mailto:Jaroslava.Schovancova@cern.ch
>>>>>>>>>>>>> <mailto:Jaroslava.Schovancova@cern.ch>>
>>>>>>>>>>>>>     >>
>>>>>>>>>>>>>
>>>>>>>>>>>>
>>>>>>>>>>>> -- 
>>>>>>>>>>>> Jaroslava Schovancová
>>>>>>>>>>>> CERN IT-CM-IS
>>>>>>>>>>>> +41754118301 (16-8301)
>>>>>>>>>>>> Jaroslava.Schovancova@cern.ch
>>>>>>>>>>>>
>>>>>>>>>>
>>>>>>>>>> -- 
>>>>>>>>>> Jaroslava Schovancová
>>>>>>>>>> CERN IT-CM-IS
>>>>>>>>>> +41754118301 (16-8301)
>>>>>>>>>> Jaroslava.Schovancova@cern.ch
>>>>>>>>>>

```

**Comment by belforte** [comment]
possible solutions:
1. somehow make SHahzad put a CRAB/bin directory in $PATH
1. add a crab createproxy command

**Comment by belforte** [comment]
a very preliminar implementation now in https://github.com/belforte/CRABClient/tree/tc

**Comment by belforte** [comment]
almost dome. Need to take care of autocompletion in
`etc/crab-bash-completion.sh`

**Comment by belforte** [comment]
autocompletion added with https://github.com/dmwm/CRABClient/pull/4950/commits/e3e15178d2640d91e2eed305b09211851f97ca51
