### ISSUE TITLE
new createmyproxy command fails 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4955]
it works for me [1]
but it fails for Andrea Sciaba' [2]

problem is related to
```
DEBUG 2020-11-09 10:38:50.503 UTC: 	 Executing : 
 command : voms-proxy-info -file ~/.globus/usercert.pem -timeleft
 output : 
 error: Proxy not found: Private key was not found in the PEM keystore (1 certificate(s) was (were) found).
```
from
```python
 File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/CRABClient/CredentialInteractions.py", line 253, in createNewMyProxy
    usercertDaysLeft = myproxy.getUserCertEnddate(openSSL=False)

```

[1]
```
DEBUG 2020-11-09 11:19:01.563 UTC: 	 CRAB Client version: v3.201104
DEBUG 2020-11-09 11:19:01.564 UTC: 	 Running on: Linux lxplus799.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-09 11:19:01.564 UTC: 	 Executing command: 'createmyproxy'
DEBUG 2020-11-09 11:19:01.565 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/belforte/.crab3
DEBUG 2020-11-09 11:19:01.570 UTC: 	 Command use: createmyproxy
DEBUG 2020-11-09 11:19:01.570 UTC: 	 Options use: ['--days=101']
DEBUG 2020-11-09 11:19:01.570 UTC: 	 Instance is None
DEBUG 2020-11-09 11:19:01.570 UTC: 	 Server base url is None
INFO 2020-11-09 11:19:01.570 UTC: 	 Checking credentials
DEBUG 2020-11-09 11:19:01.606 UTC: 	 Checking credentials
DEBUG 2020-11-09 11:19:01.607 UTC: 	 Found proxy file /tmp/x509up_u8516
DEBUG 2020-11-09 11:19:01.607 UTC: 	 Getting proxy life time left
DEBUG 2020-11-09 11:19:03.128 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u8516 -timeleft
 output : 689063

 error: 
 retcode : 0
DEBUG 2020-11-09 11:19:04.243 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u8516 -actimeleft
 output : 689062

 error: 
 retcode : 0
DEBUG 2020-11-09 11:19:04.243 UTC: 	 Proxy lifetime 689063 secs is different from voms extension lifetime 689062 secs for proxy: /tmp/x509up_u8516
DEBUG 2020-11-09 11:19:04.243 UTC: 	 Proxy valid for 191:24:22 hours
INFO 2020-11-09 11:19:04.348 UTC: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
DEBUG 2020-11-09 11:19:05.792 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u8516 -identity
 output : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it

 error: 
 retcode : 0
DEBUG 2020-11-09 11:19:05.792 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2020-11-09 11:19:05.792 UTC: 	 Calculating hash of /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it for credential name
DEBUG 2020-11-09 11:19:06.506 UTC: 	 Executing : 
 command : myproxy-info -l be1f4dc5be8664cbd145bf008f5399adf42b086f -s myproxy.cern.ch
 output : username: be1f4dc5be8664cbd145bf008f5399adf42b086f
owner: /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  timeleft: 3317:47:33  (138.2 days)

 error: 
 retcode : 0
DEBUG 2020-11-09 11:19:06.507 UTC: 	 Myproxy is valid: 11944053
DEBUG 2020-11-09 11:19:06.507 UTC: 	 Retrieving username ...
DEBUG 2020-11-09 11:19:06.507 UTC: 	 Retrieving username from CRIC...
DEBUG 2020-11-09 11:19:07.487 UTC: 	 username is belforte
DEBUG 2020-11-09 11:19:07.498 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2020-11-09 11:19:07.498 UTC: 	 using belforte_CRAB as credential login name
DEBUG 2020-11-09 11:19:07.805 UTC: 	 Executing : 
 command : myproxy-info -l belforte_CRAB -s myproxy.cern.ch
 output : username: belforte_CRAB
owner: /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  timeleft: 3317:47:38  (138.2 days)

 error: 
 retcode : 0
DEBUG 2020-11-09 11:19:07.805 UTC: 	 Myproxy is valid: 11944058
INFO 2020-11-09 11:19:07.829 UTC: 	 Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab.log
belforte@lxplus799/TC3> 

```

[2]
```
DEBUG 2020-11-09 10:39:21.946 UTC: 	 CRAB Client version: v3.201104
DEBUG 2020-11-09 10:39:21.947 UTC: 	 Running on: Linux lxplus787.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-09 10:39:21.947 UTC: 	 Executing command: 'createmyproxy'
DEBUG 2020-11-09 10:39:21.947 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/asciaba/.crab3
DEBUG 2020-11-09 10:39:21.948 UTC: 	 Command use: createmyproxy
DEBUG 2020-11-09 10:39:21.948 UTC: 	 Options use: ['--days=100']
DEBUG 2020-11-09 10:39:21.948 UTC: 	 Instance is None
DEBUG 2020-11-09 10:39:21.948 UTC: 	 Server base url is None
INFO 2020-11-09 10:39:21.948 UTC: 	 Checking credentials
DEBUG 2020-11-09 10:39:21.954 UTC: 	 Checking credentials
DEBUG 2020-11-09 10:39:21.954 UTC: 	 Found proxy file /tmp/x509up_u7026
DEBUG 2020-11-09 10:39:21.955 UTC: 	 Getting proxy life time left
DEBUG 2020-11-09 10:39:22.659 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u7026 -timeleft
 output : 43195

 error: 
 retcode : 0
DEBUG 2020-11-09 10:39:23.367 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u7026 -actimeleft
 output : 43194

 error: 
 retcode : 0
DEBUG 2020-11-09 10:39:23.367 UTC: 	 Proxy lifetime 43195 secs is different from voms extension lifetime 43194 secs for proxy: /tmp/x509up_u7026
DEBUG 2020-11-09 10:39:23.368 UTC: 	 Proxy valid for 11:59:54 hours
INFO 2020-11-09 10:39:23.453 UTC: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
DEBUG 2020-11-09 10:39:24.066 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u7026 -identity
 output : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba

 error: 
 retcode : 0
DEBUG 2020-11-09 10:39:24.067 UTC: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2020-11-09 10:39:24.067 UTC: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba for credential name
DEBUG 2020-11-09 10:39:24.271 UTC: 	 Executing : 
 command : myproxy-info -l cf6f57f3d5b5b3736a75c950392bdfad36525391 -s myproxy.cern.ch
 output : username: cf6f57f3d5b5b3736a75c950392bdfad36525391
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms0105.cern.ch|/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=(ddi|ddidk|mytw).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch
  timeleft: 2231:30:04  (93.0 days)

 error: 
 retcode : 0
DEBUG 2020-11-09 10:39:24.272 UTC: 	 Myproxy is valid: 8033404
DEBUG 2020-11-09 10:39:24.879 UTC: 	 Executing : 
 command : voms-proxy-info -file ~/.globus/usercert.pem -timeleft
 output : 
 error: Proxy not found: Private key was not found in the PEM keystore (1 certificate(s) was (were) found).

 retcode : 1
ERROR 2020-11-09 10:39:24.879 UTC: 	 Error while checking proxy timeleft for ~/.globus/usercert.pem
ERROR 2020-11-09 10:39:24.922 UTC: 	 Unhandled Exception!
ERROR 2020-11-09 10:39:24.922 UTC: 	 <@========== WMException Start ==========@>
Exception Class: CredentialException
Message: Cannot get user certificate remaining time with "voms-proxy-info"
	ModuleName : WMCore.Credential.Proxy
	MethodName : getUserCertTimeLeft
	ClassInstance : None
	FileName : /cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/WMCore/Credential/Proxy.py
	ClassName : None
	LineNumber : 221
	ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/bin/crab", line 152, in __call__
    self.cmd()
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/CRABClient/Commands/createmyproxy.py", line 43, in __call__
    proxy.createNewMyProxy(timeleftthreshold=60 * 60 * 24 * days, nokey=True)
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/CRABClient/CredentialInteractions.py", line 253, in createNewMyProxy
    usercertDaysLeft = myproxy.getUserCertEnddate(openSSL=False)
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/WMCore/Credential/Proxy.py", line 231, in getUserCertEnddate
    timeleft = self.getUserCertTimeLeft(openSSL)
  File "/cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/WMCore/Credential/Proxy.py", line 221, in getUserCertTimeLeft
    raise CredentialException('Cannot get user certificate remaining time with "voms-proxy-info"')
CredentialException: <@========== WMException Start ==========@>
Exception Class: CredentialException
Message: Cannot get user certificate remaining time with "voms-proxy-info"
	ModuleName : WMCore.Credential.Proxy
	MethodName : getUserCertTimeLeft
	ClassInstance : None
	FileName : /cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/WMCore/Credential/Proxy.py
	ClassName : None
	LineNumber : 221
	ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>
ERROR 2020-11-09 10:39:24.922 UTC: 	 ERROR: CredentialException: <@========== WMException Start ==========@>
Exception Class: CredentialException
Message: Cannot get user certificate remaining time with "voms-proxy-info"
	ModuleName : WMCore.Credential.Proxy
	MethodName : getUserCertTimeLeft
	ClassInstance : None
	FileName : /cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/lib/WMCore/Credential/Proxy.py
	ClassName : None
	LineNumber : 221
	ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>
ERROR 2020-11-09 10:39:24.922 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2020-11-09 10:39:24.922 UTC: 	 	Client Version: v3.201104
ERROR 2020-11-09 10:39:24.923 UTC: 	 	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/user/a/asciaba/crab.log to the CRAB cache.
belforte@lxplus799/TC3> 

```

**Comment by belforte** [comment]
OK.
I reproduce the error if my myproxy credential does not exist or has duration less than what requested in --days argument.
Must have done something stupid when testing initially.

**Comment by belforte** [comment]
ultimately this is is because at the time WMCore/Proxy.getUserCertTimeLeft(openSSL)
https://github.com/dmwm/WMCore/blob/51e3e2f6975b92abbbd9bf7291cf7e8d8eabd2e3/src/python/WMCore/Credential/Proxy.py#L187
was written (2014) `voms-proxy-info` was able to report the validity time left for a certificate, while it does not anymore in the Java version.

Example
```
 C++  versions

belforte@lxplus7107/TC3> voms-proxy-info2 -file ~/.globus/usercert.pem
subject   : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
issuer    : /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience Personal CA 3
identity  : /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience Personal CA 3
type      : unknown
strength  : 2048 bits
path      : /afs/cern.ch/user/b/belforte/.globus/usercert.pem
timeleft  : 4509:36:38

Java version

belforte@lxplus7107/TC3> voms-proxy-info3 -file ~/.globus/usercert.pem
Proxy not found: Private key was not found in the PEM keystore (1 certificate(s) was (were) found).
belforte@lxplus7107/TC3>

FWIW: arcproxy

belforte@lxplus7107/~> arcproxy -i validityLeft -P ~/.globus/usercert.pem
16234159 
```

OTOH, openssl works and report same output in 1.0 and 1.1 versions, so in this use case we are immune from the problem discussed in #4828 which led to #4934

```
belforte@lxplus7107/DEBUG> openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
belforte@lxplus7107/DEBUG> openssl x509 -noout -dates -in ~/.globus/usercert.pem 
notBefore=Apr 17 00:00:00 2020 GMT
notAfter=May 16 12:00:00 2021 GMT
belforte@lxplus7107/DEBUG> 

LapSB:CRABServer$ openssl version
OpenSSL 1.1.1  11 Sep 2018
LapSB:CRABServer$ openssl x509 -noout -dates -in ~/.globus/usercert.pem 
notBefore=Apr 17 00:00:00 2020 GMT
notAfter=May 16 12:00:00 2021 GMT
LapSB:CRABServer$ 

```

**Comment by belforte** [comment]
Conclusion:
this commit https://github.com/belforte/CRABClient/commit/914a0b4e7346b798852e06f0261f4842b983c2a2 in #4934 was wrong.
There is no need to remove that call, actually the call to openSSL in there is needed and can't be avoided w/o more extensive changes in the  way myproxy is handled inside WMCore/Credentials/Proxy

**Comment by belforte** [comment]
changed to critical because also crab submit may fail if there's no good credential in myproxy and voms-proxy-info is the java one
