### ISSUE TITLE
handle better exceptions from myproxy.getMyProxyTimeLeft

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4967]
In a case where the credential in myproxy has an empty list of retrievers, crab submit prints this [1] to console
but submission actually goes one because we now create two credentials and the first one went OK.
Note that a wrong ist of retrievers (some TW missing e.g.) is handled finely, only an empy one triggers the error.

The message needs to be improved to make it clear that prblem in in retrievers list, not in
getting time and that users shoud remove the existing credential an delegate again.

[1]
```
ERROR:root:Problems calculating proxy lifetime, logging stack trace and raising ProxyCreationException
Traceback (most recent call last):
  File "/home/cmsbot/CRAB/CRABClient/src/python/CRABClient/CredentialInteractions.py", line 341, in createNewMyProxy2
    myproxytimeleft = myproxy.getMyProxyTimeLeft(serverRenewer=True, nokey=nokey)
  File "/home/cmsbot/CRAB/WMCore/src/python/WMCore/Credential/Proxy.py", line 454, in getMyProxyTimeLeft
    "Unexpected result while decoding trusted retrievers list: " + str(trustedRetrList))
CredentialException: <@========== WMException Start ==========@>
Exception Class: CredentialException
Message: Unexpected result while decoding trusted retrievers list: []
	ModuleName : WMCore.Credential.Proxy
	MethodName : getMyProxyTimeLeft
	ClassInstance : None
	FileName : /home/cmsbot/CRAB/WMCore/src/python/WMCore/Credential/Proxy.py
	ClassName : None
	LineNumber : 454
	ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>
DEBUG:CRAB3.all:Result of myproxy credential check:
  Credential exists on myproxy: username: a89d85b5d3b5e016ca3701eebcb42631cde823ba  - validity: 7 days, 21:00:37
  Error trying to create credential:
 Problems calculating the time left until the expiration of the proxy. Please reset your environment or contact hn-cms-computing-tools@cern.ch if the problem persists.
Unexpected result while decoding trusted retrievers list: []
DEBUG:CRAB3.all:Command use: submit
DEBUG:CRAB3.all:Options use: []
DEBUG:CRAB3.all:CRABClient version: development
DEBUG:CRAB3.all:Instance is dev
DEBUG:CRAB3.all:Server base url is cmsweb-test2.cern.ch
DEBUG:CRAB3.all:Command url /crabserver/dev/workflow
DEBUG:CRAB3.all:Started submission

```

**Comment by belforte** [comment]
it is not critical, but if I do not fix it now that I hit it, I will never do.
