### ISSUE TITLE
v3.210422 odd failures to record tranfers

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4995]
submitting smallish tasks with few jobs goes OK.
But when I ran large tasks the transfer_fts script fails every now and thento record things
with a corrupted hostname. To be investigated
```
2021-04-23 16:05:28,901[  7691]Thread-8: Marking submitted 4 files
2021-04-23 16:05:28,902[  7692]Thread-9: Processing transfers from: T1_UK_RAL_Disk
2021-04-23 16:05:28,902[  7692]Thread-9: Submitting 1 transfers to FTS server
2021-04-23 16:05:28,951[  7741]Thread-9: Marking submitted 1 files
2021-04-23 16:05:28,951[  7741]Thread-10: Processing transfers from: T2_US_Vanderbilt
2021-04-23 16:05:28,952[  7742]Thread-10: Submitting 5 transfers to FTS server
2021-04-23 16:05:29,021[  7811]Thread-10: Marking submitted 5 files
2021-04-23 16:05:29,027[  7817]MainThread: Fatal error trying to connect to https://cmsweb-testbed.cern.ch:8443cmsweb-testbed.cern.ch:8443/crabserver/preprod//filetransfers using list_of_transfer_state=%5B%27SUBMITTED%27%2C+%27SUBMITTED%27%5D&subresource=updateTransfers&list_of_ids=%5B%27c0b0cc64b3c85742ff0147166409e4b7d8696ffb9085af1c9b5fa8c7%27%2C+%27a261bdd4a845dbbd47439f3cb3a00899b23ac4619c9d24b092a50486%27%5D&list_of_fts_id=%5B%27f1fd86f2-a43c-11eb-add8-fa163e49dbae%27%2C+%27f1fd86f2-a43c-11eb-add8-fa163e49dbae%27%5D&asoworker=schedd&list_of_fts_instance=%5B%27https%3A%2F%2Ffts3-cms.cern.ch%3A8446%2F%27%2C+%27https%3A%2F%2Ffts3-cms.cern.ch%3A8446%2F%27%5D
2021-04-23 16:05:29,027[  7817]MainThread: error during main loop
Traceback (most recent call last):
  File "task_process/FTS_Transfers.py", line 609, in <module>
    algorithm()
  File "task_process/FTS_Transfers.py", line 600, in algorithm
    new_jobs = submission_manager(rucioClient, ftsContext, crabserver)
  File "task_process/FTS_Transfers.py", line 529, in submission_manager
    _, jobids = perform_transfers("task_process/transfers.txt", last_line, _last, ftsContext, rucioClient, crabserver)
  File "task_process/FTS_Transfers.py", line 441, in perform_transfers
    jobids = submit(rucioClient, ftsContext, transfers, crabserver)
  File "task_process/FTS_Transfers.py", line 401, in submit
    data=encodeRequest(fileDoc))
  File "/data/srv/glidecondor/condor_local/spool/1559/0/cluster8611559.proc0.subproc0/CRAB3.zip/RESTInteractions.py", line 105, in post
    return self.makeRequest(uri=uri, data=data, verb='POST')
  File "/data/srv/glidecondor/condor_local/spool/1559/0/cluster8611559.proc0.subproc0/CRAB3.zip/RESTInteractions.py", line 149, in makeRequest
    verbose=self['verbose'])
  File "/data/srv/glidecondor/condor_local/spool/1559/0/cluster8611559.proc0.subproc0/CRAB3.zip/WMCore/Services/pycurl_manager.py", line 279, in request
    curl.perform()
error: (6, 'Could not resolve host: cmsweb-testbed.cern.ch:8443cmsweb-testbed.cern.ch; Name or service not known')
2021-04-23 16:05:29,028[  7818]MainThread: transfer_inject.py exiting
2021-04-23 16:10:33,941[   718]MainThread: using user's proxy from /data/srv/glidecondor/condor_local/spool/1559/0/cluster8611559.proc0.subproc0/cfa0cb32f2043a8042e1290debf652b8fd62334e
2021-04-23 16:10:34,260[  1037]MainThread: Delegating proxy to FTS...
2021-04-23 16:10:34,386[  1163]MainThread: Delegated proxy valid until 2021-04-25T10:19:56
2021-04-23 16:10:34,388[  1165]MainThread: Initializing Rucio client
2021-04-23 16:10:34,388[  1165]MainThread: Initializing Rucio client for 210423_135427:belforte_crab_20210423_155420
2021-04-23 16:10:34,389[  1166]MainThread: starting from line: 0
2021-04-23 16:10:34,540[  1318]Thread-1: Processing transfers from: T2_DE_RWTH
2021-04-23 16:10:34,542[  1319]Thread-1: Submitting 18 transfers to FTS server
2021-04-23 16:10:34,662[  1439]Thread-1: Marking submitted 18 files


```

**Comment by belforte** [comment]
damn.. it is a CRAB Server issue, not CRAB Client.
