### ISSUE TITLE
crab report should not crash if no jobs have completed

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5011]
when getting data from DBS via dasgoclient an exception is raised if
no jobs completed, likely becasue dasgoclient output is not in the expected json format
```
INFO 2021-06-01 09:44:56.216 UTC: 	 Status on the scheduler:	SUBMITTED
INFO 2021-06-01 09:44:56.217 UTC: 	 
Jobs status:                    running      		100.0% (1/1)
INFO 2021-06-01 09:44:56.217 UTC: 	 
Output dataset:			/GenericTTbar/cmsbot-autotest-1622540330-94ba0e06145abd65ccb1d21786dc7e1d/USER
INFO 2021-06-01 09:44:56.217 UTC: 	 
No publication information available yet
ERROR 2021-06-01 09:44:56.985 UTC: 	 Unhandled Exception!
ERROR 2021-06-01 09:44:56.985 UTC: 	 list index out of range
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02683/share/cms/crab-dev/v3.210505.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms-ib.cern.ch/nweek-02683/share/cms/crab-dev/v3.210505.01/bin/crab", line 138, in __call__
    self.cmd()
  File "/cvmfs/cms-ib.cern.ch/nweek-02683/share/cms/crab-dev/v3.210505.01/lib/CRABClient/Commands/report.py", line 37, in __call__
    reportData = self.collectReportData()
  File "/cvmfs/cms-ib.cern.ch/nweek-02683/share/cms/crab-dev/v3.210505.01/lib/CRABClient/Commands/report.py", line 329, in collectReportData
    repDGO = self.getDBSPublicationInfo_viaDasGoclient(reportData['outputDatasets'])
  File "/cvmfs/cms-ib.cern.ch/nweek-02683/share/cms/crab-dev/v3.210505.01/lib/CRABClient/Commands/report.py", line 452, in getDBSPublicationInfo_viaDasGoclient
    total_events = result[0]['summary'][0]['nevents']
IndexError: list index out of range
```

**Comment by belforte** [comment]
when jobs are running the `report2` output here
https://github.com/dmwm/CRABClient/blob/6e3a194a028bec7345cc319ec48178968d3deef7/src/python/CRABClient/Commands/report.py#L289
must contain `outputDatasets` info
https://github.com/dmwm/CRABClient/blob/6e3a194a028bec7345cc319ec48178968d3deef7/src/python/CRABClient/Commands/report.py#L326-L330
since `getDBSPublicationInfo_viaDasGoclient` exit w/o doing anything it this is not set
https://github.com/dmwm/CRABClient/blob/6e3a194a028bec7345cc319ec48178968d3deef7/src/python/CRABClient/Commands/report.py#L412

**Comment by belforte** [comment]
indeed before Pubisher runs this line returns `[]`
https://github.com/dmwm/CRABClient/blob/6e3a194a028bec7345cc319ec48178968d3deef7/src/python/CRABClient/Commands/report.py#L451
and therefore following line raises `*** IndexError: list index out of range`
https://github.com/dmwm/CRABClient/blob/6e3a194a028bec7345cc319ec48178968d3deef7/src/python/CRABClient/Commands/report.py#L452
