### ISSUE TITLE
modernize usef of sorted(obj,cmp=..) in status.py

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5041]
now that `status_cache` file problem is solved ( #5032 #5038  ), when running with python3 `crab status` fails with
```
    self.printDetails(statusCacheInfo, automaticSplitt, self.jobids, True, maxMemory, maxJobRuntime, numCores)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 498, in printDetails
    for jobid in sorted(jobidsToUse, cmp=compareJobids):
TypeError: 'cmp' is an invalid keyword argument for sort()
ERROR 2021-06-26 20:08:37.902 UTC: 	 ERROR: TypeError: 'cmp' is an invalid keyword argument for sort()
ERROR 2021-06-26 20:08:37.902 UTC: 	 
```
see:
https://docs.python.org/3/howto/sorting.html

**Comment by belforte** [comment]
It seems that I missed some other instance of use of `cmp` outside the `sorted` method.

```
No publication information (publication has been disabled in the CRAB configuration file)
ERROR: NameError: name 'cmp' is not defined
```
in `crab.log`:
```
ERROR 2021-06-28 09:00:37.845 UTC: 	 Unhandled Exception!
ERROR 2021-06-28 09:00:37.845 UTC: 	 name 'cmp' is not defined
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 154, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 141, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 217, in __call__
    self.printErrors(statusCacheInfo, automaticSplitt)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 792, in printErrors
    ec_jobids[ec][i] = [str(y) for y in sorted([x for x in ec_jobids[ec][i]], key=cmp_to_key(compareJobids))]
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 577, in compareJobids
    return cmp(aa[0], bb[0])
NameError: name 'cmp' is not defined
ERROR 2021-06-28 09:00:37.846 UTC: 	 ERROR: NameError: name 'cmp' is not defined

```

**Comment by belforte** [comment]
the latter thing is better addressed in its own Issue, since it has nothing to do with `sorted`: #5046
