### ISSUE TITLE
crab uploadLog fails in python3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5043]
```
belforte@lxplus796/TC3> crab uploadlog 
Will upload file /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/ste/crab_20210628_103403/crab.log.
Fetching user enviroment to log file
Uploading log file...
ERROR: TypeError: a bytes-like object is required, not 'str'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: development
	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/ste/crab_20210628_103403/crab.log to the CRAB cache.
belforte@lxplus796/TC3> 

```
the log file reports this traceback
```
INFO 2021-06-28 08:43:02.152 UTC: 	 Uploading log file...
ERROR 2021-06-28 08:43:02.161 UTC: 	 Unhandled Exception!
ERROR 2021-06-28 08:43:02.161 UTC: 	 a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 154, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 141, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/uploadlog.py", line 48, in __call__
    logfileurl = uploadlogfile(self.logger, self.proxyfilename, taskname = taskname, logfilename = logfilename, \
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 240, in uploadlogfile
    if 'S3' in cacheurl.upper():
TypeError: a bytes-like object is required, not 'str'
ERROR 2021-06-28 08:43:02.214 UTC: 	 ERROR: TypeError: a bytes-like object is required, not 'str'
```

**Comment by belforte** [comment]
same reason (and same cure) as #5044 
this time this code:
https://github.com/dmwm/CRABClient/blob/e006c6b53feff1e0a2d39b3178aeb9cf166b47ed/src/python/CRABClient/ClientUtilities.py#L234-L237
