### ISSUE TITLE
uploading tarball to S3 fails in python3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5044]
Things fail clearly for debug tarball

```
DEBUG 2021-06-28 08:47:03.239 UTC:       Making tarball in /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210628_104700/inputs/debugFiles.tgz
DEBUG 2021-06-28 08:47:03.259 UTC:       Uploading archive /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210628_104700/inputs/debugFiles.tgz (1 KB) to the CRAB cache. Using URI b'https://cmsweb-test2.cern.ch/S3/crabcache_dev'
ERROR 2021-06-28 08:47:03.259 UTC:       Problem uploading debug_files.tar.gz.
Error message: a bytes-like object is required, not 'str'.
More details can be found in /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210628_104700/crab.log
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/JobType/Analysis.py", line 188, in run
    debugFilesUploadResult = dtb.upload(filecacheurl = filecacheurl.encode('ascii', 'ignore'))
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/JobType/UserTarball.py", line 282, in upload
    if 'S3' in filecacheurl.upper():
TypeError: a bytes-like object is required, not 'str'

```

underlaying reason is likely to be the same as for #5043 

while it is not so clear for sandbox, although I presume it will also fail, but since it is usually there already, there is no actual upload attempted:
```
l
DEBUG 2021-06-28 08:49:50.744 UTC:       Uploading archive /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210628_104948/inputs/5cbd551b-ca1e-4db1-8b18-eb59fc09adc6default.tgz (15 KB) to the CRAB cache. Using URI https://cmsweb-testbed.cern.ch/S3/crabcache_preprod
DEBUG 2021-06-28 08:49:50.874 UTC:       sandbox 52b9b0ebc502b003b20435a4d5d9ce4fe07df9fe69f925cf6b1cd9975ba5f75.tar.gz is already in the S3 store, will not upload again
```

**Comment by belforte** [comment]
Actually upload of input sandbox works. The problem is only with debug_files.tar.gz

**Comment by belforte** [comment]
error come from these lines
https://github.com/dmwm/CRABClient/blob/e006c6b53feff1e0a2d39b3178aeb9cf166b47ed/src/python/CRABClient/JobType/Analysis.py#L187-L188
there is no similar convertion from unicode to ascii for the input sandbox
https://github.com/dmwm/CRABClient/blob/e006c6b53feff1e0a2d39b3178aeb9cf166b47ed/src/python/CRABClient/JobType/Analysis.py#L161-L162
since it was removed in
https://github.com/dmwm/CRABClient/pull/5024/commits/806323a2d1a09aee4151de2c3f18f0f95bab7b05

Of course I have to make sure that py3-compatible code also runs in SL6/CMSSW_6 but I think we do not use "old versions of pycurl" anymore, whatever it meant, we are forced to use new ones anyhow.

**Comment by belforte** [comment]
solved via https://github.com/dmwm/CRABClient/pull/5048
