### ISSUE TITLE
getlog fails in python3 (or more generally getFileFromURL fails)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5045]
this should be solved at the root when replacing all those various HTTP queries with
`curl` and/or `wget` via #4972

```
DEBUG 2021-06-28 08:53:33.788 UTC: 	 Command use: getlog
DEBUG 2021-06-28 08:53:33.789 UTC: 	 Options use: ['--short', '--jobids', '1', '-d', 'crab_20210628_103403/']
DEBUG 2021-06-28 08:53:33.921 UTC: 	 CRABClient version: development
DEBUG 2021-06-28 08:53:33.921 UTC: 	 Instance is dev
DEBUG 2021-06-28 08:53:33.921 UTC: 	 Server base url is cmsweb-test2.cern.ch
DEBUG 2021-06-28 08:53:33.921 UTC: 	 Command api workflow
INFO 2021-06-28 08:53:34.297 UTC: 	 Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210628_103403/results 
INFO 2021-06-28 08:53:34.297 UTC: 	 Retrieving...
ERROR 2021-06-28 08:53:34.575 UTC: 	 Unhandled Exception!
ERROR 2021-06-28 08:53:34.575 UTC: 	 write() argument must be str, not bytes
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 154, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 141, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 44, in __call__
    failed, success = self.retrieveShortLogs(webdir, self.proxyfilename)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 110, in retrieveShortLogs
    getFileFromURL(url, self.dest + '/' + filename, proxyfilename)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/UserUtilities.py", line 134, in getFileFromURL
    f.write(data)
TypeError: write() argument must be str, not bytes
ERROR 2021-06-28 08:53:34.779 UTC: 	 ERROR: TypeError: write() argument must be str, not bytes
ERROR 2021-06-28 08:53:34.780 UTC: 	 

```

**Comment by belforte** [comment]
@ddaina I assigned to you On Hold with the idea that this should be tested when you have solved #4972 If it still fails at that point.. we'll review

**Comment by belforte** [comment]
same problem also affects `crab preparelocal`

**Comment by belforte** [comment]
this will not be fixed by the rewriting of `RESTInteraction` in https://github.com/dmwm/CRABClient/issues/4972, since that is tailored for JSON data.
So I better write a small curl-based file retriever to use in
https://github.com/dmwm/CRABClient/blob/6174a5dbe53b967ce0c7371391e4ca5d230f5804/src/python/CRABClient/UserUtilities.py#L114
and
https://github.com/dmwm/CRABClient/blob/6174a5dbe53b967ce0c7371391e4ca5d230f5804/src/python/CRABClient/UserUtilities.py#L145

**Comment by belforte** [comment]
`getlog --short` is now OK.
I need to do the same for `report.py`  and `preparelocal.py`
then need to look at usate of `getDataFromURL` which will suffer of same problems and to make sure that the error handling which I put in is enough, i.e. try all sort of failures.

@ddaina we have a joint venture in curl error handling, let's try to find the best way to share code, and to make it as good as we can
 
Here's what I have put now.
https://github.com/dmwm/CRABClient/blob/aab1664c6e4214c2959c214c3499719fb2e04e44/src/python/CRABClient/UserUtilities.py#L114-L135
