### ISSUE TITLE
`cmp()` is not available in python3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5046]
this code
https://github.com/dmwm/CRABClient/blob/eb9498c7f0a05e68ff771ffa7bf1eb78b8d4b07e/src/python/CRABClient/ClientUtilities.py#L561-L577
files in python3 with
```
ERROR 2021-06-28 09:00:37.845 UTC: 	 Unhandled Exception!
ERROR 2021-06-28 09:00:37.845 UTC: 	 name 'cmp' is not defined
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 154, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 141, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 217, in __call__
    self.printErrors(statusCacheInfo, automaticSplitt)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/status.py", line 792, in printErrors
    ec_jobids[ec][i] = [str(y) for y in sorted([x for x in ec_jobids[ec][i]], key=cmp_to_key(compareJobids))]
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 577, in compareJobids
    return cmp(aa[0], bb[0])
NameError: name 'cmp' is not defined
ERROR 2021-06-28 09:00:37.846 UTC: 	 ERROR: NameError: name 'cmp' is not defined

```

**Comment by belforte** [comment]
luckily that's the only place in CRABClient where python2 `cmp()` is used. Since there is no trivial alternative in python 3  [ref](https://portingguide.readthedocs.io/en/latest/comparisons.html) , I will simply inline the needed code from https://docs.python.org/2.7/library/functions.html?highlight=cmp#cmp
```
cmp(x, y)

    Compare the two objects x and y and return an integer according to the outcome. The return value is negative if x < y, zero if x == y and strictly positive if x > y.

```
