### ISSUE TITLE
exception not properly handled in py3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5052]
some code in exception handling does not work properly in py3
```
ERROR 2021-07-01 15:01:26.928 UTC: 	 Unhandled Exception!
ERROR 2021-07-01 15:01:26.928 UTC: 	 'error' object is not subscriptable
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 157, in makeRequest
    response, datares = self['conn'].request(url, data, encode=True, headers=headers, verb=verb, doseq=True,
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 283, in request
    curl.perform()
pycurl.error: (7, 'Failed to connect to stefanovm.cern.ch port 443: No route to host')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 154, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 139, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/submit.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 370, in __init__
    self.handleMyProxy()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line 472, in handleMyProxy
    all_task_workers_dns = server_info(self.crabserver, subresource='delegatedn')
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 666, in server_info
    dictresult, dummyStatus, dummyReason = crabserver.get(api, requestdict)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 226, in get
    return self.server.get(uri, data)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 107, in get
    return self.makeRequest(uri=uri, data=data, verb='GET')
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 162, in makeRequest
    if (i < 2) or (retriableError(ex) and (i < self['retry'])):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/RESTInteractions.py", line 47, in retriableError
    return ex[0] in [28, 35]
TypeError: 'error' object is not subscriptable
ERROR 2021-07-01 15:01:27.546 UTC: 	 ERROR: TypeError: 'error' object is not subscriptable
ERROR 2021-07-01 15:01:27.547 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2021-07-01 15:01:27.547 UTC: 	 	Client Version: development
ERROR 2021-07-01 15:01:27.547 UTC: 	 	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/PY3/crab_20210701_170026/crab.log to the CRAB cache.
belforte@lxplus780/PY3> 

```
not a blocker, simply actual error is in the log rather then printed to console.

**Comment by belforte** [comment]
@ddaina well.. as you now are the happy owner of the full "make crab client work with any python"... I am adding this to your list. For a change, here I have no clue what the problem is. I guess that Dario can also help.
see also:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/6179/1/1/1.html

**Comment by mapellidario** [comment]
I did not manage to find the file `RESTInteractions.py` so that i can not guarantee 100% what I am saying, but i have the feeling that this is caused by what [pylint](https://pylint.pycqa.org/en/v2.10.2/technical_reference/features.html) warns against with

```
indexing-exception (W1624):
--
  | Indexing exceptions will not work on Python 3 Indexing exceptions will not work on Python 3. Use exception.args[index] instead.
```

**Comment by belforte** [comment]
thanks Dario, looks quite promising !
 RESTInteraction.py is imported from CRABServer repository: https://github.com/dmwm/CRABServer/blob/master/src/python/RESTInteractions.py
