### ISSUE TITLE
getoutput fails in v3.210831

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5077]
```
belforte@lxplus703/C12> crab getoutput -d ./crab_20210903_185435
Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/C12/crab_20210903_185435/results 
Retrieving 1 files
Will use `gfal-copy` command for file transfers
ERROR: NameError: name 'xrange' is not defined

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: v3.210831
	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/C12/crab_20210903_185435/crab.log to the CRAB cache.
belforte@lxplus703/C12> crab getoutput -d ./crab_20210903_185435 --jobids 1
Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/C12/crab_20210903_185435/results 
Retrieving 1 files
Will use `gfal-copy` command for file transfers
ERROR: NameError: name 'xrange' is not defined

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: v3.210831
	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/C12/crab_20210903_185435/crab.log to the CRAB cache.
belforte@lxplus703/C12> crab --version
CRAB client v3.210831
belforte@lxplus703/C12> 

```

**Comment by belforte** [comment]
log file
```
DEBUG 2021-09-03 20:21:50.080 UTC: 	 CRABClient version: v3.210831
DEBUG 2021-09-03 20:21:50.080 UTC: 	 Instance is dev
DEBUG 2021-09-03 20:21:50.080 UTC: 	 Server base url is cmsweb-test2.cern.ch
DEBUG 2021-09-03 20:21:50.080 UTC: 	 Command api workflow
INFO 2021-09-03 20:21:50.085 UTC: 	 Will use `gfal-copy` command for file transfers
DEBUG 2021-09-03 20:21:50.124 UTC: 	 Starting ChildProcess with 10 ChildProcess
ERROR 2021-09-03 20:21:50.146 UTC: 	 Unhandled Exception!
ERROR 2021-09-03 20:21:50.146 UTC: 	 name 'xrange' is not defined
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/bin/crab", line 150, in <module>
    client()
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/bin/crab", line 137, in __call__
    self.cmd()
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/lib/CRABClient/Commands/getoutput.py", line 15, in __call__
    returndict = getcommand.__call__(self, subresource = 'data2')
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/lib/CRABClient/Commands/getcommand.py", line 138, in __call__
    successdict, faileddict = copyoutput()
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/lib/CRABClient/Commands/remote_copy.py", line 110, in __call__
    inputq, processarray = self.startchildproc(self.processWorker, nsubprocess, successfiles, failedfiles)
  File "/cvmfs/cms-ib.cern.ch/nweek-02696/share/cms/crab-dev/v3.210831.00/lib/CRABClient/Commands/remote_copy.py", line 189, in startchildproc
    for i in xrange(nsubprocess):
NameError: name 'xrange' is not defined

```

**Comment by belforte** [comment]
some old developer tried to overoptimize things using `xrange` where `range` was plenty. 
Eventually in python3 they got rid of having two functions for same goal https://stackoverflow.com/questions/15014310/why-is-there-no-xrange-function-in-python3
