### ISSUE TITLE
crab-dev status fails at some sites

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5084]
e.g. at FLNALLPC
```
cmslpc130:WORK$ crab-dev status 
CRAB project directory:		/uscms/homes/b/belforte/WORK/crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1
Task name:			211005_220936:chpapage_crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1
Grid scheduler - Task Worker:	crab3@vocms0107.cern.ch - crab-prod-tw02
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-testbed.cern.ch/crabserver/ui/task/211005_220936%3Achpapage_crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=chpapage&var-task=211005_220936%3Achpapage_crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1&from=1633468177000&to=now
Format error in status_cache. Empty file ?
ERROR: TypeError: 'NoneType' object is not subscriptable

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: v3.210909
	Please use 'crab uploadlog' to upload the log file /uscms/homes/b/belforte/WORK/crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1/crab.log to the CRAB cache.
cmslpc130:WORK$ 
```
looking at logs it comes from
```
ERROR 2021-10-06 17:15:12.268 UTC: 	 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-dev/v3.210909.00/bin/crab", line 150, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-dev/v3.210909.00/bin/crab", line 137, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/share/cms/crab-dev/v3.210909.00/lib/CRABClient/Commands/status.py", line 225, in __call__
    combinedStatus = dagStatus = self.printDAGStatus(dbStatus, statusCacheInfo)
  File "/cvmfs/cms.cern.ch/share/cms/crab-dev/v3.210909.00/lib/CRABClient/Commands/status.py", line 396, in printDAGStatus
    dagInfo = statusCacheInfo['DagStatus']
TypeError: 'NoneType' object is not subscriptable
ERROR 2021-10-06 17:15:12.270 UTC: 	 ERROR: TypeError: 'NoneType' object is not subscriptable
ERROR 2021-10-06 17:15:12.270 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2021-10-06 17:15:12.270 UTC: 	 	Client Version: v3.210909
ERROR 2021-10-06 17:15:12.270 UTC: 	 	Please use 'crab uploadlog' to upload the log file /uscms/homes/b/belforte/WORK/crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1/crab.log to the CRAB cache.

```

I can reproduce this outside crab:
```
cmslpc130:WORK$ curl -sS --cert /uscms/home/belforte/x509up_u6423 --key /uscms/home/belforte/x509up_u6423 -o /tmp/status-cache-qc218rfa.pkl -w %"{http_code}" "https://cmsweb.cern.ch:8443/scheddmon/0107/cms128/211005_220936:chpapage_crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1/status_cache.pkl"
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```
and fix is shamefully simple, just add ` --capath /etc/grid-security/certificates/`
```
cmslpc130:WORK$ curl -sS  --capath /etc/grid-security/certificates/ --cert /uscms/home/belforte/x509up_u6423 --key /uscms/home/belforte/x509up_u6423 -o /tmp/status-cache-qc218rfa.pkl -w %"{http_code}" "https://cmsweb.cern.ch:8443/scheddmon/0107/cms128/211005_220936:chpapage_crab_CloseByDoubleGamma_E25Eta1p88Delta2p5_CMSSW_12_0_2_upgrade2026_D76_clue3D_tag1_step1/status_cache.pkl"
200cmslpc130:WORK$ 

```

**Comment by belforte** [comment]
the offending curl call comes form `curlGetFileFromURL` in
https://github.com/dmwm/CRABClient/blob/6c34a951989a037a9493d81afea0dbe6f36fbf4e/src/python/CRABClient/UserUtilities.py#L118
