### ISSUE TITLE
curl argument list too long for large number of runs to analyse

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#5105]
CRABClient in current HEAD: when trying to use CRAB config parameter `runrage` which involves high but still allowed number of runs to analyze, i.e. less than 50000 https://github.com/dmwm/CRABClient/blob/fd44f41134c46bdcb1db4d6c3a60c09b04234609/src/python/CRABClient/JobType/Analysis.py#L234 fails to submit task with following error:
```
[ddirmait@lxplus798 lumilist_tests]$ crab submit  lumilist5.py
Will use CRAB configuration file lumilist5.py
Importing CMSSW configuration pset_tutorial_analysis_TEST.py
Finished importing CMSSW configuration pset_tutorial_analysis_TEST.py
Sending the request to the server at cmsweb-testbed.cern.ch
ERROR: OSError: [Errno 7] Argument list too long: '/bin/sh'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: development
	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/user/d/ddirmait/crab_tasks/lumilist_tests/crab_projects/crab_20211104_112107/crab.log to the CRAB cache.
```

from task log:
```
ERROR 2021-11-04 10:21:10.038 UTC:       Unhandled Exception!
ERROR 2021-11-04 10:21:10.038 UTC:       [Errno 7] Argument list too long: '/bin/sh'
Traceback (most recent call last):
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/bin/crab.py", line 149, in <module>
    client()
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/bin/crab.py", line 136, in __call__
    self.cmd()
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/src/python/CRABClient/Commands/submit.py", line 132, in __call__
    dictresult, status, reason = server.put(api=self.defaultApi, data=self.configreq_encoded)
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/src/python/CRABClient/CrabRestInterface.py", line 236, in put
    return self.server.put(uri, data)
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/src/python/CRABClient/CrabRestInterface.py", line 107, in put
    return self.makeRequest(uri=uri, data=data, verb='PUT')
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/src/python/CRABClient/CrabRestInterface.py", line 159, in makeRequest
    stdout, stderr, curlExitCode = execute_command(command=command, logger=self.logger)
  File "/afs/cern.ch/user/d/ddirmait/git/CRABClient/src/python/CRABClient/ClientUtilities.py", line 788, in execute_command
    proc = subprocess.Popen(
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python3/3.9.6/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python3/3.9.6/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
ERROR 2021-11-04 10:21:10.040 UTC:       ERROR: OSError: [Errno 7] Argument list too long: '/bin/sh'
```

**Comment by belforte** [comment]
how long was the list ?

**Comment by ddaina** [comment]
i was testing edge cases, so initially i had max allowed number of runs which is 50000. but it fails also for `config.Data.runRange = '1-5000'` runs

**Comment by belforte** [comment]
I doubt this was ever tested with that many runs. IIUC client expands that into a list of 5000 strings, so header is likely so long to be rejected by cmsweb anyhow. That expansion surely sounds silly, but we don't want to change client/rest protocol now.
Can you try with current client ?
We should put a small limit like 10 and direct to use a lumimask instead.

**Comment by ddaina** [comment]
>  Can you try with current client ?

current client submits the task
