### ISSUE TITLE
 bytes vs. string in crab killl by operator

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5127]
I do not know if this is to be fixed on client or server side.
It is indeed an almost never used funcionality !!

```
belforte@lxplus7101/C12> crab kill -d  crab_20211202_104835 --killwarning 'killed by Stefano'
ERROR: TypeError: a bytes-like object is required, not 'str'

```

see also https://github.com/dmwm/CRABServer/issues/6896
once understood where problem is, close of these two identical tkts. Unless solution requires a change in both

**Comment by belforte** [comment]
it is a client problem, which only appears when running the client in python3 (for CMSSW_12).
Traceback:
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02710/share/cms/crab-dev/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms-ib.cern.ch/nweek-02710/share/cms/crab-dev/v3.211130.01/bin/crab.py", line 136, in __call__
    self.cmd()
  File "/cvmfs/cms-ib.cern.ch/nweek-02710/share/cms/crab-dev/v3.211130.01/lib/CRABClient/Commands/kill.py", line 29, in __call__
    inputs.update({'killwarning' : b64encode(self.options.killwarning)})
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python3/3.9.6/lib/python3.9/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
ERROR 2021-12-10 14:23:50.992 UTC: 	 ERROR: TypeError: a bytes-like object is required, not 'str'

```

**Comment by belforte** [comment]
@mapellidario  how can we deal with `b64encode` here
https://github.com/dmwm/CRABClient/blob/c5ddf6608eb62264797bc7af7dc5fc51d63e67a9/src/python/CRABClient/Commands/kill.py#L29

to make it py3 compatible w/o using `encodeUnicodeToBytes` from Utils ?
I have no problem in using an `if` like already a few lines above
https://github.com/dmwm/CRABClient/blob/c5ddf6608eb62264797bc7af7dc5fc51d63e67a9/src/python/CRABClient/Commands/kill.py#L6-L9

or maybe we can simply do for any interpreter
```python
 b64encode(self.options.killwarning.encode('utf-8'))
```
?

**Comment by belforte** [comment]
the simpler "add encodeutf-8" appears sufficient in one quick test in CMSSW_12 and CMSSW_10
