### ISSUE TITLE
latest tag fails with production server

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5145]
while things work with preprod and test. When using prod I get in the client
```
belforte@lxplus773/bot> crab-dev status 
BEWARE: this is the development version of CRAB Client.
Be sure to have a good reason for using it

CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220118_224721
Task name:			220118_214728:cmsbot_crab_20220118_224721
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/220118_214728%3Acmsbot_crab_20220118_224721
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=cmsbot&var-task=220118_214728%3Acmsbot_crab_20220118_224721&from=1642538848000&to=now
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (10/10)
Fatal error trying to connect to https://cmsweb.cern.ch:8443/crabserver/prod/workflow?username=cmsbot&subresource=publicationstatus&workflow=220118_214728%3Acmsbot_crab_20220118_224721 using username=cmsbot&subresource=publicationstatus&workflow=220118_214728%3Acmsbot_crab_20220118_224721.
The server answered with an error.
Server answered with: Execution error
Error Id: 4e53d608fcd69f183496c90a339df41f
belforte@lxplus773/bot> 
```

indeed simply looking up https://cmsweb.cern.ch:8443/crabserver/prod/workflow?username=cmsbot&subresource=publicationstatus&workflow=220118_214728%3Acmsbot_crab_20220118_224721 in the browser fails with HTPP 500, while replacing cmsweb with cmsweb-testbed it works. cmsweb-tezstbed is currently running py3.220117

server side log:
```
[18/Jan/2022:23:30:32]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 923a2d7dcccadfa938cd98af15c31b6d (Exe
cution error)
[18/Jan/2022:23:30:32]    Traceback (most recent call last):
[18/Jan/2022:23:30:32]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/
site-packages/WMCore/REST/Format.py", line 259, in stream_chunked
[18/Jan/2022:23:30:32]        % (obj, type(obj), str(exp)))
[18/Jan/2022:23:30:32]    UnboundLocalError: local variable 'obj' referenced before assignment
[18/Jan/2022:23:30:32]  SERVER HTTP ERROR cherrypy._cperror.HTTPError 37a73ef7b8d7cce09ccabcddaaaf9047 ((500, 'Execution error'))
[18/Jan/2022:23:30:32]    Traceback (most recent call last):
[18/Jan/2022:23:30:32]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/WMCore/REST/Server.py", line 727, in default
[18/Jan/2022:23:30:32]        return self._call(RESTArgs(list(args), kwargs))
[18/Jan/2022:23:30:32]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/WMCore/REST/Server.py", line 843, in _call
[18/Jan/2022:23:30:32]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[18/Jan/2022:23:30:32]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/WMCore/REST/Format.py", line 603, in stream_maybe_etag
[18/Jan/2022:23:30:32]        raise cherrypy.HTTPError(int(err), message)
[18/Jan/2022:23:30:32]    HTTPError: (500, 'Execution error')
[18/Jan/2022:23:30:32] crabserver-54bc876f97-hzx49 188.185.120.166 "GET /crabserver/prod/workflow?username=cmsbot&subresource=publicationstatus&workflow=220118_214728%3Acmsbot_crab_20220118_224721 HTTP/1.1" 500 Internal Server Error [data: 1551 in 745 out 66177 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "CRABClient/development" ]

```
production version of client `crab-prod` works finely.
```
belforte@lxplus773/bot> crab status 
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220118_224721
Task name:			220118_214728:cmsbot_crab_20220118_224721
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/220118_214728%3Acmsbot_crab_20220118_224721
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=cmsbot&var-task=220118_214728%3Acmsbot_crab_20220118_224721&from=1642538848000&to=now
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (10/10)

Publication status of 1 dataset(s):	done         		100.0% (10/10)
(from CRAB internal bookkeeping in transferdb)

Output dataset:			/GenericTTbar/cmsbot-CRAB3_analysis-2201-94ba0e06145abd65ccb1d21786dc7e1d/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FGenericTTbar%2Fcmsbot-CRAB3_analysis-2201-94ba0e06145abd65ccb1d21786dc7e1d%2FUSER&instance=prod%2Fphys03

Warning: the max jobs runtime is less than 30% of the task requested value (1250 min), please consider to request a lower value for failed jobs (allowed through crab resubmit) and/or improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task.

Warning: the average jobs CPU efficiency is less than 50%, please consider to improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task

Summary of run jobs:
 * Memory: 27MB min, 192MB max, 65MB ave
 * Runtime: 0:02:42 min, 0:02:43 max, 0:02:42 ave
 * CPU eff: 2% min, 10% max, 7% ave
 * Waste: 0:39:34 (59% of total)

Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220118_224721/crab.log
belforte@lxplus773/bot> 
```

**Comment by belforte** [comment]
looks like a problem with https://github.com/dmwm/CRABClient/issues/5143 somehow I had only tested against newer CRAB REST server.

**Comment by belforte** [comment]
At this point best action course is to wait for production REST to be updated to ptyhon3 branch as we run now in preprod, at which time crab-dev will work and we can look into moving it to production to complete asoDB/URL cleanup.

**Comment by belforte** [comment]
Production REST was updated one week ago.
Sent Jenkins ClientValidation + CrabConfigurationValidation with DEV client and PROD instance for all CMSSW releases in the list:

- [ ] https://github.com/dmwm/CRABServer/issues/7017  CMSSW_12
- [ ] https://github.com/dmwm/CRABServer/issues/7018  CMSSW_11
- [ ] https://github.com/dmwm/CRABServer/issues/7019  CMSSW_10
- [ ] https://github.com/dmwm/CRABServer/issues/7020  CMSSW_9
- [ ] https://github.com/dmwm/CRABServer/issues/7021  CMSSW_8
- [ ] https://github.com/dmwm/CRABServer/issues/7022  CMSSW_7_6
- [ ] https://github.com/dmwm/CRABServer/issues/7023  CMSSW_7_1

**Comment by belforte** [comment]
Full validation completed and successful for `crab-dev` and current production server
```
CRAB client v3.220104
 {"crabserver": "Welcome", "version": "py3.220124"}
```
