### ISSUE TITLE
make it clear when user's config has an error

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5299]
the user only got this at the console
```
Importing CMSSW configuration crab_configs_singleLep2016UL/runFWLJMet_shifts_XX1400H800.py
ERROR: IndexError: list index out of range
```

while the log is more clear, but nobody looks at it
```
DEBUG 2024-03-31 00:13:01.694 UTC: 	 self.config.JobType.psetName: crab_configs_singleLep2016UL/runFWLJMet_shifts_XX1400H200.py
INFO 2024-03-31 00:13:01.694 UTC: 	 Importing CMSSW configuration crab_configs_singleLep2016UL/runFWLJMet_shifts_XX1400H200.py
ERROR 2024-03-31 00:13:01.877 UTC: 	 Unhandled Exception!
ERROR 2024-03-31 00:13:01.877 UTC: 	 list index out of range
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02830/share/cms/crab-dev/v3.240216.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02830/share/cms/crab-dev/v3.240216.00/bin/crab.py", line 137, in __call__
    returnDict = self.cmd()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02830/share/cms/crab-dev/v3.240216.00/lib/CRABClient/Commands/submit.py", line 107, in __call__
    dummy_inputfiles, jobconfig = plugjobtype.run(filecacheurl)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02830/share/cms/crab-dev/v3.240216.00/lib/CRABClient/JobType/Analysis.py", line 92, in run
    userConfig=self.config.JobType.psetName)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02830/share/cms/crab-dev/v3.240216.00/lib/CRABClient/JobType/CMSSWConfig.py", line 87, in __init__
    self.fullConfig = imp.load_module(cfgBaseName, configFile, pathname, description)
  File "/uscms_data/d3/fsimpson/scratch/CMSSW_10_6_29/src/FWLJMET/LJMet/CRAB3/crab_configs_singleLep2016UL/runFWLJMet_shifts_XX1400H200.py", line 172, in <module>
    process.GlobalTag = GlobalTag(process.GlobalTag, "", "106X_mcRun2_asymptotic_v17" )
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/python/Configuration/AlCa/GlobalTag.py", line 113, in GlobalTag
    record     = entry[1]
IndexError: list index out of range
ERROR 2024-03-31 00:13:01.878 UTC: 	 ERROR: IndexError: list index out of range
ERROR 2024-03-31 00:13:01.878 UTC: 	 
	Please email cmstalk+computing-tools@dovecotmta.cern.ch for support with the crab.log file or crab.log URL.
ERROR 2024-03-31 00:13:01.878 UTC: 	 	Client Version: v3.240216
```

We should print that info to the console when an exception happens importing user's config.

**Comment by belforte** [comment]
😲 
**THANK YOU**

**Comment by belforte** [comment]
thanks @aspiringmind-code .  console output now is as desired. [1]
But I preferred to add this explicit traceback only in this case where the problem is clearly in the user file, rather than doing every time if I were to put it in the `CRABClient/log_exception` method. Somehow sticking to the original idea that user errors are handled and "clearly reported", while uncaught exceptions indicate a bug and are better kept inside log only, so that users
 1. are not confused
 2. are encouraged to send us full log, so we can understand, rather than just one or two lines

[1]
```console
belforte@lxplus800/TC3> crab submit 
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration dummyanalyzer.py
ERROR: python exception inside CMSSW configuration file dummyanalyzer
 name 'b' is not defined
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/JobType/CMSSWConfig.py", line 88, in __init__
    self.fullConfig = load_module(cfgBaseName, modRef)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/cern.ch/work/b/belforte/CRAB3/TC3/dummyanalyzer.py", line 5, in <module>
    a=b
NameError: name 'b' is not defined
ERROR: NameError: name 'b' is not defined

 Look for more details in crab.log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20250624_113656/crab.log
  If you can't figure out the problem, please send email to
	cmstalk+computing-tools@dovecotmta.cern.ch with the crab.log file or crab.log URL.
  Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20250624_113656/crab.log to the CRAB cache.
belforte@lxplus800/TC3> 
```
